//! Task: install AI plugin manifests via Microsoft APM.
//!
//! See <https://github.com/microsoft/apm>.  The dotfiles repo ships an
//! `apm/config/base.yml` under `symlinks/` which is linked to
//! `~/.apm/config/base.yml` by the
//! [`InstallSymlinks`](super::symlinks::InstallSymlinks) task.  Overlay
//! repositories may symlink additional fragments into `~/.apm/config/*.yml`
//! (for example `~/.apm/config/work.yml`).
//!
//! Because `apm install -g --target copilot,vscode` always reads the manifest
//! at `~/.apm/apm.yml` regardless of cwd, this task merges every
//! `~/.apm/config/*.yml` fragment into a single generated `~/.apm/apm.yml`
//! and then invokes `apm install -g --target copilot,vscode` once so primitives
//! deploy globally to both the Copilot target (`~/.copilot/`) and the VS Code
//! target (`~/.vscode/`).  Idempotency is provided by APM itself via its
//! lockfile; the merged file is regenerated deterministically every run.

use anyhow::{Context as _, Result};
use std::path::{Path, PathBuf};

use crate::phases::{Context, Task, TaskPhase, TaskResult, task_deps};

/// Header written at the top of the generated `~/.apm/apm.yml`.  The contents
/// are not meaningful to APM itself beyond providing a valid manifest, but
/// the warning helps anyone who opens the file by hand.
const GENERATED_HEADER: &str =
    "# Generated by dotfiles from ~/.apm/config/*.yml fragments.\n# Manual edits will be lost.\n";

/// Install AI plugin manifests via Microsoft APM (`apm install -g --target copilot,vscode`).
#[derive(Debug)]
pub struct InstallApmPackages;

impl Task for InstallApmPackages {
    fn name(&self) -> &'static str {
        "Install APM packages"
    }

    fn phase(&self) -> TaskPhase {
        TaskPhase::Apply
    }

    task_deps![
        super::packages::InstallPackages,
        super::packages::InstallAurPackages,
        super::symlinks::InstallSymlinks
    ];

    fn should_run(&self, ctx: &Context) -> bool {
        // Run whenever the symlinks layer ships at least one fragment
        // (the repo's `apm/config/base.yml`), or whenever fragments have
        // been linked into `~/.apm/config/`.
        ctx.config_read()
            .root
            .join("symlinks")
            .join("apm")
            .join("config")
            .join("base.yml")
            .exists()
            || !discover_fragment_files(&ctx.home).is_empty()
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        if ctx.dry_run {
            return Ok(TaskResult::DryRun);
        }

        if !ctx.executor.which("apm") {
            let reason = "apm not found in PATH; install it via `winget install Microsoft.APM` \
                          on Windows or the `apm-bin` AUR package on Arch Linux"
                .to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let fragments = discover_fragment_files(&ctx.home);
        if fragments.is_empty() {
            let reason = "no manifest fragments found under ~/.apm/config/".to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let merged = merge_fragments(&fragments)?;
        write_merged_manifest(&ctx.home.join(".apm").join("apm.yml"), &merged)?;

        let cwd = ctx.home.clone();
        ctx.debug_fmt(|| {
            format!(
                "running `apm install -g --target copilot,vscode` in {} (interactive credential \
                 prompts disabled)",
                cwd.display()
            )
        });
        // Disable interactive credential prompts from git and Git Credential
        // Manager so a missing GitHub token causes apm install to fail fast
        // instead of blocking on a popup.
        let env: &[(&str, &str)] = &[
            ("GIT_TERMINAL_PROMPT", "0"),
            ("GCM_INTERACTIVE", "Never"),
            ("GCM_GUI_PROMPT", "false"),
        ];
        match ctx.executor.run_in_with_env(
            &cwd,
            "apm",
            &["install", "-g", "--target", "copilot,vscode"],
            env,
        ) {
            Ok(result) => {
                report_apm_output(ctx, &result.stdout, &result.stderr);
                Ok(TaskResult::Ok)
            }
            Err(err) => {
                let msg = format!("{err:#}");
                if looks_like_auth_failure(&msg) {
                    let reason = "apm install requires GitHub authentication; run \
                                  `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                        .to_string();
                    ctx.log
                        .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                    Ok(TaskResult::Skipped(reason))
                } else {
                    Err(err)
                }
            }
        }
    }
}

/// Surface `apm install` output to the user so they can see what was
/// installed (or that nothing changed).  APM provides idempotency itself
/// via its lockfile, so we have to relay its output to give the user any
/// visibility into the install — otherwise the task is silent on success.
fn report_apm_output(ctx: &Context, stdout: &str, stderr: &str) {
    let mut emitted = false;
    for line in stdout.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.info(trimmed);
        emitted = true;
    }
    for line in stderr.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.warn(trimmed);
        emitted = true;
    }
    if !emitted {
        ctx.log.info("apm install completed (no output)");
    }
}

/// Discover `*.yml` and `*.yaml` files in `~/.apm/config/`.
///
/// Returns an empty vector if the directory does not exist.  Results are
/// sorted by path so the merged manifest is deterministic regardless of the
/// filesystem's enumeration order.
fn discover_fragment_files(home: &Path) -> Vec<PathBuf> {
    let config_dir = home.join(".apm").join("config");
    let Ok(entries) = std::fs::read_dir(&config_dir) else {
        return Vec::new();
    };
    let mut files: Vec<PathBuf> = entries
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let path = entry.path();
            let is_yaml = path
                .extension()
                .and_then(|ext| ext.to_str())
                .is_some_and(|ext| {
                    ext.eq_ignore_ascii_case("yml") || ext.eq_ignore_ascii_case("yaml")
                });
            (is_yaml && path.is_file()).then_some(path)
        })
        .collect();
    files.sort();
    files
}

/// Parse each fragment, concatenate `dependencies.apm` and `dependencies.mcp`
/// across all of them, and emit a single YAML document string.
fn merge_fragments(fragments: &[PathBuf]) -> Result<String> {
    use serde_yaml_ng::Value;

    let mut apm_deps: Vec<Value> = Vec::new();
    let mut mcp_deps: Vec<Value> = Vec::new();

    for path in fragments {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("reading manifest fragment {}", path.display()))?;
        if content.trim().is_empty() {
            continue;
        }
        let value: Value = serde_yaml_ng::from_str(&content)
            .with_context(|| format!("parsing manifest fragment {}", path.display()))?;

        if let Some(deps) = value.get("dependencies") {
            if let Some(seq) = deps.get("apm").and_then(Value::as_sequence) {
                apm_deps.extend(seq.iter().cloned());
            }
            if let Some(seq) = deps.get("mcp").and_then(Value::as_sequence) {
                mcp_deps.extend(seq.iter().cloned());
            }
        }
    }

    let mut root = serde_yaml_ng::Mapping::new();
    root.insert(Value::from("name"), Value::from("dotfiles"));
    root.insert(Value::from("version"), Value::from("1.0.0"));

    let mut deps = serde_yaml_ng::Mapping::new();
    if !apm_deps.is_empty() {
        deps.insert(Value::from("apm"), Value::Sequence(apm_deps));
    }
    if !mcp_deps.is_empty() {
        deps.insert(Value::from("mcp"), Value::Sequence(mcp_deps));
    }
    if !deps.is_empty() {
        root.insert(Value::from("dependencies"), Value::Mapping(deps));
    }

    let body = serde_yaml_ng::to_string(&Value::Mapping(root))
        .context("serialising merged apm manifest")?;
    Ok(format!("{GENERATED_HEADER}{body}"))
}

/// Write the merged manifest to `target`, replacing any existing file or
/// symlink (e.g. a leftover symlink from the previous direct-link layout).
///
/// Returns early without writing if the existing file already has identical
/// content, so we avoid bumping the mtime on unchanged runs.
fn write_merged_manifest(target: &Path, content: &str) -> Result<()> {
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating directory {}", parent.display()))?;
    }

    // Check existing content; only rewrite if changed.  We use symlink_metadata
    // first because the legacy layout had `~/.apm/apm.yml` as a symlink into
    // the dotfiles repo, and we want to replace it with a real file.
    match std::fs::symlink_metadata(target) {
        Ok(meta) if meta.file_type().is_symlink() => {
            std::fs::remove_file(target)
                .with_context(|| format!("removing legacy symlink {}", target.display()))?;
        }
        Ok(_) => {
            if let Ok(existing) = std::fs::read_to_string(target)
                && existing == content
            {
                return Ok(());
            }
        }
        Err(_) => {}
    }

    std::fs::write(target, content)
        .with_context(|| format!("writing merged manifest {}", target.display()))
}

/// Heuristic: does an `apm install` failure message indicate a missing or
/// invalid GitHub credential rather than a real installation error?
fn looks_like_auth_failure(message: &str) -> bool {
    let lowered = message.to_lowercase();
    [
        "authentication",
        "could not read username",
        "could not read password",
        "terminal prompts disabled",
        "401",
        "403",
        "fatal: authentication failed",
        "credential",
    ]
    .iter()
    .any(|needle| lowered.contains(needle))
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    reason = "test code uses panicking helpers"
)]
mod tests {
    use super::*;
    use crate::phases::test_helpers::{ContextBuilder, empty_config, make_linux_context};
    use std::path::PathBuf;
    #[test]
    fn should_run_false_when_no_fragments() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);
        assert!(!InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn should_run_true_when_repo_base_yml_exists() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let base = dir.path().join("symlinks").join("apm").join("config");
        std::fs::create_dir_all(&base).expect("create symlinks/apm/config dir");
        std::fs::write(base.join("base.yml"), "name: test\n").expect("write base.yml");
        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);
        assert!(InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn should_run_true_when_only_overlay_fragment_in_home() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let cfg = dir.path().join(".apm").join("config");
        std::fs::create_dir_all(&cfg).expect("create ~/.apm/config dir");
        std::fs::write(cfg.join("work.yml"), "name: work\n").expect("write work.yml");
        let config = empty_config(dir.path().to_path_buf());
        let ctx = ContextBuilder::new(config)
            .build()
            .with_home(dir.path().to_path_buf());
        assert!(InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn run_skips_when_apm_not_found() {
        let config = empty_config(PathBuf::from("/tmp"));
        let ctx = make_linux_context(config);
        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        match result {
            TaskResult::Skipped(reason) => assert!(
                reason.contains("apm not found"),
                "expected reason to mention 'apm not found', got {reason:?}"
            ),
            other => panic!("expected TaskResult::Skipped, got {other:?}"),
        }
    }

    #[test]
    fn discover_fragment_files_returns_empty_when_dir_missing() {
        let dir = tempfile::tempdir().expect("create temp dir");
        assert!(discover_fragment_files(dir.path()).is_empty());
    }

    #[test]
    fn discover_fragment_files_returns_yaml_files_only_sorted() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let cfg = dir.path().join(".apm").join("config");
        std::fs::create_dir_all(&cfg).expect("create config dir");
        std::fs::write(cfg.join("work.yml"), "name: work\n").expect("write work.yml");
        std::fs::write(cfg.join("base.yaml"), "name: base\n").expect("write base.yaml");
        std::fs::write(cfg.join("README.md"), "ignore me\n").expect("write README.md");

        let files = discover_fragment_files(dir.path());
        assert_eq!(files.len(), 2);
        assert!(files[0].ends_with("base.yaml"));
        assert!(files[1].ends_with("work.yml"));
    }

    #[test]
    fn merge_fragments_concatenates_apm_and_mcp_dependencies() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let a = dir.path().join("a.yml");
        let b = dir.path().join("b.yml");
        std::fs::write(
            &a,
            "name: a\nversion: 1.0.0\ndependencies:\n  apm:\n    - foo/bar\n",
        )
        .expect("write a");
        std::fs::write(
            &b,
            "name: b\nversion: 1.0.0\ndependencies:\n  apm:\n    - baz/qux\n  mcp:\n    - server-1\n",
        )
        .expect("write b");

        let merged = merge_fragments(&[a, b]).expect("merge");
        assert!(merged.starts_with(GENERATED_HEADER));
        assert!(merged.contains("foo/bar"));
        assert!(merged.contains("baz/qux"));
        assert!(merged.contains("server-1"));
        assert!(merged.contains("name: dotfiles"));
    }

    #[test]
    fn merge_fragments_preserves_complex_map_entries() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("complex.yml");
        std::fs::write(
            &f,
            "name: x\nversion: 1.0.0\ndependencies:\n  apm:\n    - git: dev.azure.com/org/repo\n      path: services/foo\n",
        )
        .expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert!(merged.contains("dev.azure.com/org/repo"));
        assert!(merged.contains("services/foo"));
    }

    #[test]
    fn merge_fragments_skips_empty_files() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("empty.yml");
        std::fs::write(&f, "\n\n").expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert!(merged.contains("name: dotfiles"));
        assert!(!merged.contains("dependencies:"));
    }

    #[test]
    fn write_merged_manifest_replaces_legacy_symlink() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let target = dir.path().join("apm.yml");
        let source = dir.path().join("source.yml");
        std::fs::write(&source, "old\n").expect("write source");

        // Skip on platforms where unprivileged symlink creation isn't
        // available (Windows without developer mode).
        #[cfg(unix)]
        std::os::unix::fs::symlink(&source, &target).expect("symlink");
        #[cfg(windows)]
        if std::os::windows::fs::symlink_file(&source, &target).is_err() {
            return;
        }

        write_merged_manifest(&target, "new content\n").expect("write");
        let meta = std::fs::symlink_metadata(&target).expect("stat");
        assert!(
            !meta.file_type().is_symlink(),
            "should no longer be a symlink"
        );
        assert_eq!(
            std::fs::read_to_string(&target).expect("read"),
            "new content\n"
        );
    }

    #[test]
    fn write_merged_manifest_skips_rewrite_when_unchanged() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let target = dir.path().join("apm.yml");
        std::fs::write(&target, "same\n").expect("seed");
        let mtime_before = std::fs::metadata(&target)
            .expect("stat")
            .modified()
            .expect("mtime");
        // Sleep briefly so a rewrite would change mtime measurably.
        std::thread::sleep(std::time::Duration::from_millis(10));
        write_merged_manifest(&target, "same\n").expect("write");
        let mtime_after = std::fs::metadata(&target)
            .expect("stat")
            .modified()
            .expect("mtime");
        assert_eq!(mtime_before, mtime_after);
    }
}
