//! Task: install AI plugin manifests via Microsoft APM.
//!
//! See <https://github.com/microsoft/apm>.  The dotfiles repo ships an
//! `apm/config/base.yml` under `symlinks/` which is linked to
//! `~/.apm/config/base.yml` by the
//! [`InstallSymlinks`](super::symlinks::InstallSymlinks) task.  Overlay
//! repositories may symlink additional fragments into `~/.apm/config/*.yml`
//! (for example `~/.apm/config/work.yml`).
//!
//! Because `apm install -g --target copilot,vscode` always reads
//! the manifest
//! at `~/.apm/apm.yml` regardless of cwd, this task merges every
//! `~/.apm/config/*.yml` fragment into a single generated `~/.apm/apm.yml`.
//! It then invokes
//! `apm install -g --target copilot,vscode` whenever install state
//! must be materialized, including ordinary up-to-date runs so local symlinked
//! plugin edits are redeployed to their real runtime locations.
//! Idempotency is provided by APM itself via its lockfile; the merged file is
//! regenerated deterministically every run.
//!
//! The experimental `copilot-app` target is intentionally **not** enabled: in
//! apm 0.16.0 it aborts the whole install (exit 1) by trying to lockfile-encode
//! agent primitives (`*.agent.md`) as Copilot App workflows, which lack the
//! mandatory `apm--` id namespace. Re-enable it once that upstream bug is fixed.

use anyhow::{Context as _, Result};
use sha2::{Digest as _, Sha256};
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use crate::phases::{Context, Task, TaskPhase, TaskResult, task_deps};

/// Header written at the top of the generated `~/.apm/apm.yml`.  The contents
/// are not meaningful to APM itself beyond providing a valid manifest, but
/// the warning helps anyone who opens the file by hand.
const GENERATED_HEADER: &str =
    "# Generated by dotfiles from ~/.apm/config/*.yml fragments.\n# Manual edits will be lost.\n";
const APM_TARGETS: &str = "copilot,vscode";
const APM_NONINTERACTIVE_ENV: &[(&str, &str)] = &[
    ("GIT_TERMINAL_PROMPT", "0"),
    ("GCM_INTERACTIVE", "Never"),
    ("GCM_GUI_PROMPT", "false"),
];
const APM_UP_TO_DATE_MARKER: &str = "all dependencies are up-to-date";

/// Install and update AI plugin manifests via Microsoft APM.
#[derive(Debug)]
pub struct InstallApmPackages;

impl Task for InstallApmPackages {
    fn name(&self) -> &'static str {
        "Install APM packages"
    }

    fn phase(&self) -> TaskPhase {
        TaskPhase::Apply
    }

    task_deps![
        super::packages::InstallPackages,
        super::packages::InstallAurPackages,
        super::symlinks::InstallSymlinks
    ];

    fn should_run(&self, ctx: &Context) -> bool {
        // Run whenever the symlinks layer ships fragments, or whenever
        // fragments have been linked into `~/.apm/config/`.
        let repo_config_dir = ctx
            .config_read()
            .root
            .join("symlinks")
            .join("apm")
            .join("config");
        match discover_yaml_files(&repo_config_dir) {
            Ok(fragments) if !fragments.is_empty() => return true,
            Ok(_) => {}
            Err(err) => {
                ctx.log.warn(&format!(
                    "could not inspect symlinks/apm/config; task will run to avoid hiding the \
                     error: {err:#}"
                ));
                return true;
            }
        }

        match discover_fragment_files(&ctx.home) {
            Ok(fragments) => !fragments.is_empty(),
            Err(err) => {
                ctx.log.warn(&format!(
                    "could not inspect ~/.apm/config; task will run to surface the error: {err:#}"
                ));
                true
            }
        }
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        if !ctx.dry_run && !ctx.executor.which("apm") {
            let reason = "apm not found in PATH; install it via `winget install Microsoft.APM` \
                          on Windows or the `apm-bin` AUR package on Arch Linux"
                .to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let fragments = discover_fragment_files(&ctx.home)?;
        if fragments.is_empty() {
            let reason = "no manifest fragments found under ~/.apm/config/".to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let manifest_path = ctx.home.join(".apm").join("apm.yml");
        let lock_path = ctx.home.join(".apm").join("apm.lock.yaml");
        let marker_path = ctx.home.join(".apm").join(".dotfiles-manifest.sha256");
        let merged = merge_fragments(&fragments)?;
        let manifest_hash = manifest_fingerprint(&merged);
        let manifest_needs_write = merged_manifest_needs_write(&manifest_path, &merged)?;
        let lock_missing = !lock_path
            .try_exists()
            .with_context(|| format!("checking APM lockfile {}", lock_path.display()))?;
        let marker_missing_or_stale = !manifest_marker_matches(&marker_path, &manifest_hash)?;

        if ctx.dry_run {
            if manifest_needs_write {
                ctx.log.dry_run(&format!(
                    "merge {} APM manifest fragment(s) into {}",
                    fragments.len(),
                    manifest_path.display()
                ));
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} to sync changed manifest"
                ));
            } else if lock_missing {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} because {} is missing",
                    lock_path.display()
                ));
            } else if marker_missing_or_stale {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} because the current manifest has \
                     not been installed successfully yet"
                ));
            } else {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} to redeploy current manifest content"
                ));
                ctx.log
                    .dry_run("run apm outdated -g and update only if dependencies are stale");
            }
            return Ok(TaskResult::DryRun);
        }

        if manifest_needs_write || lock_missing || marker_missing_or_stale {
            if manifest_needs_write {
                write_merged_manifest(&manifest_path, &merged)?;
            }
            let result = run_apm_install(ctx)?;
            if matches!(result, TaskResult::Ok) {
                ctx.log
                    .always(&format!("    install: {}", describe_dependencies(&merged)));
                write_manifest_marker(&marker_path, &manifest_hash)?;
            }
            return Ok(result);
        }

        // Unchanged manifest: redeploy locally symlinked plugins without
        // announcing a state change, matching the quiet idempotent convention
        // used by the other apply tasks.
        let result = run_apm_install(ctx)?;
        if !matches!(result, TaskResult::Ok) {
            return Ok(result);
        }
        write_manifest_marker(&marker_path, &manifest_hash)?;

        match apm_dependencies_are_outdated(ctx)? {
            ApmOutdatedCheck::Outdated(true) => {
                let result = run_apm_update(ctx)?;
                if matches!(result, TaskResult::Ok) {
                    ctx.log.always("    update: APM dependencies");
                }
                Ok(result)
            }
            ApmOutdatedCheck::Outdated(false) => {
                ctx.log.debug("APM dependencies are up-to-date");
                Ok(TaskResult::Ok)
            }
            ApmOutdatedCheck::Skipped(reason) => Ok(TaskResult::Skipped(reason)),
        }
    }
}

/// Result of checking the lockfile for stale dependencies.
enum ApmOutdatedCheck {
    /// The check completed and reported whether dependencies are outdated.
    Outdated(bool),
    /// The check could not run because credentials are unavailable.
    Skipped(String),
}

/// Install the current user-scope manifest without refreshing locked refs.
fn run_apm_install(ctx: &Context) -> Result<TaskResult> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm install -g --target {APM_TARGETS}` in {} (interactive credential prompts \
             disabled)",
            cwd.display()
        )
    });
    match ctx.executor.run_in_with_env(
        &cwd,
        "apm",
        &["install", "-g", "--target", APM_TARGETS],
        APM_NONINTERACTIVE_ENV,
    ) {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(TaskResult::Ok)
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm install requires GitHub authentication; run \
                              `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log
                    .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                Ok(TaskResult::Skipped(reason))
            } else {
                Err(err).context("running apm install")
            }
        }
    }
}

/// Return whether any locked user-scope dependency has a newer matching ref.
fn apm_dependencies_are_outdated(ctx: &Context) -> Result<ApmOutdatedCheck> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| format!("running `apm outdated -g` in {}", cwd.display()));
    match ctx
        .executor
        .run_in_with_env(&cwd, "apm", &["outdated", "-g"], APM_NONINTERACTIVE_ENV)
    {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(ApmOutdatedCheck::Outdated(outdated_output_has_updates(
                &result.stdout,
                &result.stderr,
            )))
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm outdated requires GitHub authentication; run \
                              `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log.warn(&format!(
                    "skipping APM update check: {reason} (details: {})",
                    msg.trim()
                ));
                Ok(ApmOutdatedCheck::Skipped(reason))
            } else {
                Err(err).context("checking for outdated APM dependencies")
            }
        }
    }
}

/// Refresh locked user-scope dependencies to the latest matching refs.
fn run_apm_update(ctx: &Context) -> Result<TaskResult> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm deps update -g --target {APM_TARGETS}` in {} (interactive credential \
             prompts disabled)",
            cwd.display()
        )
    });
    match ctx.executor.run_in_with_env(
        &cwd,
        "apm",
        &["deps", "update", "-g", "--target", APM_TARGETS],
        APM_NONINTERACTIVE_ENV,
    ) {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(TaskResult::Ok)
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm update requires GitHub authentication; run \
                                  `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log
                    .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                Ok(TaskResult::Skipped(reason))
            } else {
                Err(err).context("updating APM dependencies")
            }
        }
    }
}

/// Return whether `apm outdated` reported any stale dependency.
fn outdated_output_has_updates(stdout: &str, stderr: &str) -> bool {
    let output = format!("{stdout}\n{stderr}").to_lowercase();
    !output.contains(APM_UP_TO_DATE_MARKER)
}

/// Build a stable fingerprint for the generated manifest content.
fn manifest_fingerprint(content: &str) -> String {
    let mut hash = String::with_capacity(64);
    for byte in Sha256::digest(content.as_bytes()) {
        hash.push(hex_nibble(byte >> 4));
        hash.push(hex_nibble(byte & 0x0f));
    }
    hash
}

/// Convert a 4-bit value to a lowercase hexadecimal character.
const fn hex_nibble(nibble: u8) -> char {
    match nibble {
        0 => '0',
        1 => '1',
        2 => '2',
        3 => '3',
        4 => '4',
        5 => '5',
        6 => '6',
        7 => '7',
        8 => '8',
        9 => '9',
        10 => 'a',
        11 => 'b',
        12 => 'c',
        13 => 'd',
        14 => 'e',
        15 => 'f',
        _ => '?',
    }
}

/// Return whether the marker records a successful install for this manifest.
fn manifest_marker_matches(marker: &Path, manifest_hash: &str) -> Result<bool> {
    match std::fs::read_to_string(marker) {
        Ok(existing) => Ok(existing.trim() == manifest_hash),
        Err(err) if err.kind() == ErrorKind::NotFound => Ok(false),
        Err(err) => Err(err)
            .with_context(|| format!("reading APM manifest install marker {}", marker.display())),
    }
}

/// Record that APM successfully installed the current generated manifest.
fn write_manifest_marker(marker: &Path, manifest_hash: &str) -> Result<()> {
    if let Some(parent) = marker.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating directory {}", parent.display()))?;
    }
    std::fs::write(marker, format!("{manifest_hash}\n"))
        .with_context(|| format!("writing APM manifest install marker {}", marker.display()))
}

/// Relay raw APM command output to the diagnostic log file and the verbose
/// console.
///
/// The headline state-change is emitted separately as an always-visible
/// `    {verb}: {desc}` line by the caller, so this routes APM's own
/// line-by-line chatter through `debug`: it is always captured in the log
/// file and shown under `--verbose`, but stays out of the way on ordinary
/// runs.  APM provides idempotency itself via its lockfile, so this output is
/// purely informational.
fn report_apm_output(ctx: &Context, stdout: &str, stderr: &str) {
    for line in stdout.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.debug(trimmed);
    }
    for line in stderr.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.debug(trimmed);
    }
}

/// Discover `*.yml` and `*.yaml` files in `~/.apm/config/`.
///
/// Returns an empty vector if the directory does not exist.  Results are
/// sorted by path so the merged manifest is deterministic regardless of the
/// filesystem's enumeration order.
fn discover_fragment_files(home: &Path) -> Result<Vec<PathBuf>> {
    discover_yaml_files(&home.join(".apm").join("config"))
}

/// Discover YAML files in an APM fragment directory.
fn discover_yaml_files(config_dir: &Path) -> Result<Vec<PathBuf>> {
    let entries = match std::fs::read_dir(config_dir) {
        Ok(entries) => entries,
        Err(err) if err.kind() == ErrorKind::NotFound => return Ok(Vec::new()),
        Err(err) => {
            return Err(err)
                .with_context(|| format!("reading APM config directory {}", config_dir.display()));
        }
    };

    let mut files = Vec::new();
    for entry in entries {
        let entry = entry
            .with_context(|| format!("reading directory entry in {}", config_dir.display()))?;
        let path = entry.path();
        if !is_yaml_fragment(&path) {
            continue;
        }
        let metadata = std::fs::metadata(&path).with_context(|| {
            format!("reading metadata for manifest fragment {}", path.display())
        })?;
        if metadata.is_file() {
            files.push(path);
        }
    }
    files.sort();
    Ok(files)
}

/// Build a human-facing phrase describing the dependencies in the merged
/// manifest, e.g. `"3 APM dependencies"` or `"1 APM dependency"`.
///
/// Used for the always-visible install change line so the console output
/// matches the `    {verb}: {desc}` style emitted by the other apply tasks.
/// Falls back to `"APM manifest"` when the count cannot be determined.
fn describe_dependencies(merged: &str) -> String {
    match count_manifest_dependencies(merged) {
        Some(1) => "1 APM dependency".to_string(),
        Some(n) => format!("{n} APM dependencies"),
        None => "APM manifest".to_string(),
    }
}

/// Count the `dependencies.apm` and `dependencies.mcp` entries in the merged
/// manifest.  Returns `None` if the manifest cannot be parsed.
fn count_manifest_dependencies(merged: &str) -> Option<usize> {
    use serde_yaml_ng::Value;

    let value: Value = serde_yaml_ng::from_str(merged).ok()?;
    let deps = value.get("dependencies")?;
    let count = ["apm", "mcp"]
        .iter()
        .filter_map(|key| deps.get(key).and_then(Value::as_sequence))
        .map(Vec::len)
        .sum();
    Some(count)
}

/// Return whether a path has a YAML extension supported by APM fragments.
fn is_yaml_fragment(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| ext.eq_ignore_ascii_case("yml") || ext.eq_ignore_ascii_case("yaml"))
}

/// Parse each fragment, concatenate `dependencies.apm` and `dependencies.mcp`
/// across all of them, and emit a single YAML document string.
fn merge_fragments(fragments: &[PathBuf]) -> Result<String> {
    use serde_yaml_ng::Value;

    let mut apm_deps: Vec<Value> = Vec::new();
    let mut mcp_deps: Vec<Value> = Vec::new();

    for path in fragments {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("reading manifest fragment {}", path.display()))?;
        if content.trim().is_empty() {
            continue;
        }
        let value: Value = serde_yaml_ng::from_str(&content)
            .with_context(|| format!("parsing manifest fragment {}", path.display()))?;

        if let Some(deps) = value.get("dependencies") {
            if let Some(seq) = deps.get("apm").and_then(Value::as_sequence) {
                apm_deps.extend(seq.iter().cloned());
            }
            if let Some(seq) = deps.get("mcp").and_then(Value::as_sequence) {
                mcp_deps.extend(seq.iter().cloned());
            }
        }
    }

    let mut root = serde_yaml_ng::Mapping::new();
    root.insert(Value::from("name"), Value::from("dotfiles"));
    root.insert(Value::from("version"), Value::from("1.0.0"));

    let mut deps = serde_yaml_ng::Mapping::new();
    if !apm_deps.is_empty() {
        deps.insert(Value::from("apm"), Value::Sequence(apm_deps));
    }
    if !mcp_deps.is_empty() {
        deps.insert(Value::from("mcp"), Value::Sequence(mcp_deps));
    }
    if !deps.is_empty() {
        root.insert(Value::from("dependencies"), Value::Mapping(deps));
    }

    let body = serde_yaml_ng::to_string(&Value::Mapping(root))
        .context("serialising merged apm manifest")?;
    Ok(format!("{GENERATED_HEADER}{body}"))
}

/// Return whether the generated manifest should be written to disk.
fn merged_manifest_needs_write(target: &Path, content: &str) -> Result<bool> {
    match std::fs::symlink_metadata(target) {
        Ok(meta) if meta.file_type().is_symlink() => {
            anyhow::bail!(
                "merged manifest target is a symlink; remove it before continuing: {}",
                target.display()
            );
        }
        Ok(meta) if meta.is_file() => {
            let existing = std::fs::read(target).with_context(|| {
                format!("reading existing merged manifest {}", target.display())
            })?;
            Ok(existing != content.as_bytes())
        }
        Ok(_) => Ok(true),
        Err(err) if err.kind() == ErrorKind::NotFound => Ok(true),
        Err(err) => Err(err)
            .with_context(|| format!("reading metadata for merged manifest {}", target.display())),
    }
}

/// Write the merged manifest to `target`, replacing any existing file.
///
/// Returns early without writing if the existing file already has identical
/// content, so we avoid bumping the mtime on unchanged runs.
fn write_merged_manifest(target: &Path, content: &str) -> Result<()> {
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating directory {}", parent.display()))?;
    }

    // Check existing content; only rewrite if changed. Use symlink_metadata so
    // a symlink is rejected instead of writing through it.
    match std::fs::symlink_metadata(target) {
        Ok(meta) if meta.file_type().is_symlink() => {
            anyhow::bail!(
                "merged manifest target is a symlink; remove it before continuing: {}",
                target.display()
            );
        }
        Ok(meta) if meta.is_file() => {
            let existing = std::fs::read(target).with_context(|| {
                format!("reading existing merged manifest {}", target.display())
            })?;
            if existing == content.as_bytes() {
                return Ok(());
            }
        }
        Ok(_) => {}
        Err(err) if err.kind() == ErrorKind::NotFound => {}
        Err(err) => {
            return Err(err).with_context(|| {
                format!("reading metadata for merged manifest {}", target.display())
            });
        }
    }

    std::fs::write(target, content)
        .with_context(|| format!("writing merged manifest {}", target.display()))
}

/// Heuristic: does an `apm install` failure message indicate a missing or
/// invalid GitHub credential rather than a real installation error?
fn looks_like_auth_failure(message: &str) -> bool {
    let lowered = message.to_lowercase();
    [
        "authentication failed",
        "authentication required",
        "bad credentials",
        "could not read username",
        "could not read password",
        "fatal: authentication failed",
        "requires authentication",
        "terminal prompts disabled",
        "401 unauthorized",
        "403 forbidden",
    ]
    .iter()
    .any(|needle| lowered.contains(needle))
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    reason = "test code uses panicking helpers"
)]
mod tests {
    use super::*;
    use crate::exec::{ExecResult, MockExecutor};
    use crate::phases::test_helpers::{empty_config, make_context, make_linux_context};
    use crate::platform::{Os, Platform};
    use std::sync::Arc;

    fn ok_result(stdout: &str) -> ExecResult {
        ExecResult {
            stdout: stdout.to_string(),
            stderr: String::new(),
            success: true,
            code: Some(0),
        }
    }

    const DEFAULT_FRAGMENT: &str =
        "name: base\nversion: 1.0.0\ndependencies:\n  apm:\n    - example/plugin\n";

    fn write_fragment(dir: &Path, filename: &str, content: &str) {
        std::fs::create_dir_all(dir).expect("create fragment dir");
        std::fs::write(dir.join(filename), content).expect("write manifest fragment");
    }

    fn write_repo_fragment(root: &Path, filename: &str, content: &str) {
        write_fragment(
            &root.join("symlinks").join("apm").join("config"),
            filename,
            content,
        );
    }

    fn write_home_fragment(home: &Path, filename: &str, content: &str) {
        write_fragment(&home.join(".apm").join("config"), filename, content);
    }

    fn write_default_home_fragment(home: &Path) {
        write_home_fragment(home, "base.yml", DEFAULT_FRAGMENT);
    }

    fn write_current_manifest_and_lock(home: &Path) {
        write_default_home_fragment(home);
        let fragments = discover_fragment_files(home).expect("discover fragments");
        let merged = merge_fragments(&fragments).expect("merge fragments");
        std::fs::write(home.join(".apm").join("apm.yml"), merged).expect("write manifest");
        std::fs::write(home.join(".apm").join("apm.lock.yaml"), "lock\n").expect("write lock");
    }

    fn write_current_manifest_lock_and_marker(home: &Path) {
        write_current_manifest_and_lock(home);
        let manifest =
            std::fs::read_to_string(home.join(".apm").join("apm.yml")).expect("read manifest");
        write_manifest_marker(
            &home.join(".apm").join(".dotfiles-manifest.sha256"),
            &manifest_fingerprint(&manifest),
        )
        .expect("write marker");
    }

    fn make_home_context(home: &Path) -> Context {
        make_linux_context(empty_config(home.to_path_buf())).with_home(home.to_path_buf())
    }

    fn make_home_context_with_executor(home: &Path, executor: MockExecutor) -> Context {
        make_context(
            empty_config(home.to_path_buf()),
            Platform::new(Os::Linux, false),
            Arc::new(executor),
        )
        .with_home(home.to_path_buf())
    }

    #[test]
    fn should_run_false_when_no_fragments() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let ctx = make_home_context(dir.path());
        assert!(!InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn should_run_true_when_repo_yaml_fragment_exists() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_repo_fragment(dir.path(), "team.yaml", "name: test\n");
        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);
        assert!(InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn should_run_true_when_only_overlay_fragment_in_home() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "work.yml", "name: work\n");
        let ctx = make_home_context(dir.path());
        assert!(InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn run_skips_when_apm_not_found() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "base.yml", "name: base\n");

        let ctx = make_home_context(dir.path());
        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        match result {
            TaskResult::Skipped(reason) => assert!(
                reason.contains("apm not found"),
                "expected reason to mention 'apm not found', got {reason:?}"
            ),
            other => panic!("expected TaskResult::Skipped, got {other:?}"),
        }
    }

    #[test]
    fn run_installs_when_manifest_changed() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(
            dir.path(),
            "base.yml",
            "name: base\nversion: 1.0.0\ndependencies:\n  apm:\n    - github/awesome-copilot/plugins/project-planning\n",
        );

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["install", "-g", "--target", "copilot,vscode"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                assert!(env.contains(&("GCM_INTERACTIVE", "Never")));
                assert!(env.contains(&("GCM_GUI_PROMPT", "false")));
                Ok(ok_result("installed\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after apm install, got {result:?}"
        );
        let manifest = std::fs::read_to_string(dir.path().join(".apm").join("apm.yml"))
            .expect("read merged manifest");
        assert!(manifest.contains("github/awesome-copilot/plugins/project-planning"));
    }

    #[test]
    fn run_reinstalls_then_skips_update_when_manifest_lock_and_dependencies_are_current() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_lock_and_marker(dir.path());

        let mut seq = mockall::Sequence::new();
        let mut mock = MockExecutor::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["install", "-g", "--target", "copilot,vscode"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("installed\n"))
            });
        let outdated_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, outdated_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["outdated", "-g"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[*] All dependencies are up-to-date\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after reinstalling current APM content, got {result:?}"
        );
    }

    #[test]
    fn run_updates_dependencies_when_outdated_reports_stale_lock() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_lock_and_marker(dir.path());

        let mut seq = mockall::Sequence::new();
        let mut mock = MockExecutor::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["install", "-g", "--target", "copilot,vscode"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("installed\n"))
            });
        let outdated_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, _env| {
                assert_eq!(dir, outdated_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["outdated", "-g"]);
                Ok(ok_result("Outdated dependencies:\n- example/plugin\n"))
            });
        let update_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, update_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["deps", "update", "-g", "--target", "copilot,vscode"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("updated\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after apm deps update, got {result:?}"
        );
    }

    #[test]
    fn run_installs_when_success_marker_is_missing() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_and_lock(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, _env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["install", "-g", "--target", "copilot,vscode"]);
                Ok(ok_result("installed\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after installing unmarked manifest, got {result:?}"
        );
        assert!(
            dir.path()
                .join(".apm")
                .join(".dotfiles-manifest.sha256")
                .exists(),
            "successful install should write the manifest success marker"
        );
    }

    #[test]
    fn run_dry_run_reports_planned_apm_work_without_writing() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let ctx = make_home_context(dir.path()).with_dry_run(true);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::DryRun),
            "expected DryRun with fragments present, got {result:?}"
        );
        assert!(
            !dir.path().join(".apm").join("apm.yml").exists(),
            "dry-run must not write the generated manifest"
        );
    }

    #[test]
    fn run_skips_auth_failures() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, _, _| {
                Err(anyhow::anyhow!(
                    "fatal: Authentication failed; terminal prompts disabled"
                ))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages
            .run(&ctx)
            .expect("auth failure should skip");
        match result {
            TaskResult::Skipped(reason) => assert!(
                reason.contains("GitHub authentication"),
                "expected auth skip reason, got {reason:?}"
            ),
            other => panic!("expected TaskResult::Skipped, got {other:?}"),
        }
    }

    #[test]
    fn run_propagates_non_auth_apm_failures() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, _, _| Err(anyhow::anyhow!("archive extraction failed")));

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let err = InstallApmPackages
            .run(&ctx)
            .expect_err("non-auth failures should propagate");
        assert!(
            format!("{err:#}").contains("archive extraction failed"),
            "expected propagated APM failure, got {err:#}"
        );
    }

    #[test]
    fn auth_failure_detection_matches_specific_auth_messages() {
        assert!(looks_like_auth_failure(
            "git failed: HTTP 403 Forbidden while fetching repository"
        ));
        assert!(looks_like_auth_failure(
            "fatal: Authentication failed; terminal prompts disabled"
        ));
    }

    #[test]
    fn auth_failure_detection_ignores_unrelated_credential_text() {
        assert!(!looks_like_auth_failure(
            "credential cache cleanup failed after archive extraction"
        ));
    }

    #[test]
    fn discover_fragment_files_returns_empty_when_dir_missing() {
        let dir = tempfile::tempdir().expect("create temp dir");
        assert!(
            discover_fragment_files(dir.path())
                .expect("discover")
                .is_empty()
        );
    }

    #[test]
    fn discover_fragment_files_errors_when_config_path_is_not_directory() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let apm_dir = dir.path().join(".apm");
        std::fs::create_dir_all(&apm_dir).expect("create ~/.apm");
        std::fs::write(apm_dir.join("config"), "not a directory\n").expect("write config file");

        let err = discover_fragment_files(dir.path()).expect_err("config file should error");
        assert!(
            format!("{err:#}").contains("reading APM config directory"),
            "expected context for read_dir failure, got {err:#}"
        );
    }

    #[test]
    fn discover_fragment_files_returns_yaml_files_only_sorted() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let cfg = dir.path().join(".apm").join("config");
        std::fs::create_dir_all(&cfg).expect("create config dir");
        std::fs::write(cfg.join("work.yml"), "name: work\n").expect("write work.yml");
        std::fs::write(cfg.join("base.yaml"), "name: base\n").expect("write base.yaml");
        std::fs::write(cfg.join("README.md"), "ignore me\n").expect("write README.md");

        let files = discover_fragment_files(dir.path()).expect("discover");
        assert_eq!(files.len(), 2);
        assert!(files[0].ends_with("base.yaml"));
        assert!(files[1].ends_with("work.yml"));
    }

    #[test]
    fn merge_fragments_concatenates_apm_and_mcp_dependencies() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let a = dir.path().join("a.yml");
        let b = dir.path().join("b.yml");
        std::fs::write(
            &a,
            "name: a\nversion: 1.0.0\ndependencies:\n  apm:\n    - foo/bar\n",
        )
        .expect("write a");
        std::fs::write(
            &b,
            "name: b\nversion: 1.0.0\ndependencies:\n  apm:\n    - baz/qux\n  mcp:\n    - server-1\n",
        )
        .expect("write b");

        let merged = merge_fragments(&[a, b]).expect("merge");
        assert!(merged.starts_with(GENERATED_HEADER));
        assert!(merged.contains("foo/bar"));
        assert!(merged.contains("baz/qux"));
        assert!(merged.contains("server-1"));
        assert!(merged.contains("name: dotfiles"));
    }

    #[test]
    fn merge_fragments_preserves_complex_map_entries() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("complex.yml");
        std::fs::write(
            &f,
            "name: x\nversion: 1.0.0\ndependencies:\n  apm:\n    - git: dev.azure.com/org/repo\n      path: services/foo\n",
        )
        .expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert!(merged.contains("dev.azure.com/org/repo"));
        assert!(merged.contains("services/foo"));
    }

    #[test]
    fn merge_fragments_skips_empty_files() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("empty.yml");
        std::fs::write(&f, "\n\n").expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert!(merged.contains("name: dotfiles"));
        assert!(!merged.contains("dependencies:"));
    }

    #[test]
    fn describe_dependencies_counts_apm_and_mcp_entries() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("deps.yml");
        std::fs::write(
            &f,
            "name: d\nversion: 1.0.0\ndependencies:\n  apm:\n    - foo/bar\n    - baz/qux\n  mcp:\n    - server-1\n",
        )
        .expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert_eq!(count_manifest_dependencies(&merged), Some(3));
        assert_eq!(describe_dependencies(&merged), "3 APM dependencies");
    }

    #[test]
    fn describe_dependencies_uses_singular_for_one_entry() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("one.yml");
        std::fs::write(
            &f,
            "name: o\nversion: 1.0.0\ndependencies:\n  apm:\n    - foo/bar\n",
        )
        .expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert_eq!(describe_dependencies(&merged), "1 APM dependency");
    }

    #[test]
    fn describe_dependencies_falls_back_when_no_dependencies() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let f = dir.path().join("none.yml");
        std::fs::write(&f, "name: n\nversion: 1.0.0\n").expect("write");
        let merged = merge_fragments(&[f]).expect("merge");
        assert_eq!(count_manifest_dependencies(&merged), None);
        assert_eq!(describe_dependencies(&merged), "APM manifest");
    }

    #[test]
    fn write_merged_manifest_errors_when_target_is_symlink() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let target = dir.path().join("apm.yml");
        let source = dir.path().join("source.yml");
        std::fs::write(&source, "old\n").expect("write source");

        // Skip on platforms where unprivileged symlink creation isn't
        // available (Windows without developer mode).
        #[cfg(unix)]
        std::os::unix::fs::symlink(&source, &target).expect("symlink");
        #[cfg(windows)]
        if std::os::windows::fs::symlink_file(&source, &target).is_err() {
            return;
        }

        let result = write_merged_manifest(&target, "new content\n");
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("symlink"),
            "error should identify symlink target: {msg}"
        );
        let meta = std::fs::symlink_metadata(&target).expect("stat");
        assert!(
            meta.file_type().is_symlink(),
            "symlink should be left untouched"
        );
    }

    #[test]
    fn write_merged_manifest_skips_rewrite_when_unchanged() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let target = dir.path().join("apm.yml");
        std::fs::write(&target, "same\n").expect("seed");
        let mtime_before = std::fs::metadata(&target)
            .expect("stat")
            .modified()
            .expect("mtime");
        // Sleep briefly so a rewrite would change mtime measurably.
        std::thread::sleep(std::time::Duration::from_millis(10));
        write_merged_manifest(&target, "same\n").expect("write");
        let mtime_after = std::fs::metadata(&target)
            .expect("stat")
            .modified()
            .expect("mtime");
        assert_eq!(mtime_before, mtime_after);
    }
}
