#!/bin/sh

# Symlink SSH keys for WSL
ssh-wsl()
{
  if [ -n "$(command -vp wslpath)" ]
  then
    for i in github vsts
    do
      if [ -d "$WINHOME"/.ssh/"$i" ] && [ "$(readlink -f "$WINHOME"/.ssh/"$i")" != "$(readlink -f "$HOME"/.ssh/"$i")" ]
      then
        ln -snvf "$WINHOME"/.ssh/"$i" "$HOME"/.ssh/"$i"
      fi
    done
  else
    echo "ERROR: Not in WSL environment" 1>&2
    return 1
  fi
}