#!/bin/bash

# Extract archives
extract()
{
  if [[ -z $1 ]]
  then
    echo "Usage: extract <file>"
    echo
    echo "Supported types: tar.bz2 tar.gz tar tbz2 tgz zip"
  elif [[ ! -f $1 ]]
  then
    echo "'$1' is not a valid file"
  else
    case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
      *.tar.bz2)  tar -jxvf "$1"                      ;;
      *.tar.gz)   tar -zxvf "$1"                      ;;
      *.tar)      tar -xvf "$1"                       ;;
      *.tbz2)     tar -jxvf "$1"                      ;;
      *.tgz)      tar -zxvf "$1"                      ;;
      *.zip)      unzip "$1"                          ;;
      *)          >&2 echo "File cannot be extracted" ;;
    esac
  fi
}

# List largest files
lf()
{
  if [[ -z $1 ]]
  then
    echo "Usage: lf <directory>"
  elif [[ ! -d $1 ]]
  then
    echo "'$1' is not a valid directory"
  else
    find "$1" -type f -exec du -a {} + | sort -nr | numfmt --to=iec --padding=4
  fi
}

# Generate ssh key for GitHub
github-key()
{
  mkdir -p $HOME/.ssh/github
  ssh-keygen -t rsa -P "" -C "$(git config --global user.email)" -f $HOME/.ssh/github/id_rsa
}