#!/bin/sh

# Extract archives
extract()
{
  if [ -z "$1" ]
  then
    echo "Usage: extract <file>"
    echo
    echo "Supported types: tar.bz2 tar.gz tar tbz2 tgz zip"
  elif [ ! -f "$1" ]
  then
    echo "'$1' is not a valid file"
  else
    case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
      *.tar.bz2)  tar -jxvf "$1"                      ;;
      *.tar.gz)   tar -zxvf "$1"                      ;;
      *.tar)      tar -xvf "$1"                       ;;
      *.tbz2)     tar -jxvf "$1"                      ;;
      *.tgz)      tar -zxvf "$1"                      ;;
      *.zip)      unzip "$1"                          ;;
      *)          >&2 echo "File cannot be extracted" ;;
    esac
  fi
}

# Generate ssh key for GitHub
githubkey()
{
  mkdir -p "$HOME"/.ssh/github
  ssh-keygen -t rsa -b 4096 -P "" -C "$(git config --global user.email)" -f "$HOME"/.ssh/github/id_rsa
}

# Symlink SSH keys for WSL
if [ -n "$(command -vp wslpath)" ]
then
  wslsshkey()
  {
    for i in github vsts
    do
      if [ -d "$WINHOME"/.ssh/"$i" ] && [ "$(readlink -f "$WINHOME"/.ssh/"$i")" != "$(readlink -f "$HOME"/.ssh/"$i")" ]
      then
        ln -snvf "$WINHOME"/.ssh/"$i" "$HOME"/.ssh/"$i"
      fi
    done
  }
fi
