#!/bin/sh

# Check if git parent process is the shell to determine pinentry program
# shellcheck disable=SC2046  # Word splitting intentional for ps arguments
# shellcheck disable=SC2009  # ps+grep pattern needed to check parent process
if ps h --format comm $(ps -C git -o ppid=) | grep -qxP "$(basename "$SHELL")" \
  && [ -x /usr/bin/pinentry-curses ]
then
  exec /usr/bin/pinentry-curses "$@"
fi

if [ -f /usr/lib/libgtk-x11-2.0.so.0 ] \
  && [ -x /usr/bin/pinentry-gnome3 ]
then
  exec /usr/bin/pinentry-gnome3 "$@"
fi