version: 2

updates:
  - package-ecosystem: cargo
    directory: /cli
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - sneivandt
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - sneivandt
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - sneivandt
    groups:
      docker-images:
        patterns:
          - "*"
    ignore:
      - dependency-name: rust
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: ubuntu
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
          - version-update:semver-patch
