#!/bin/bash

for terminal in urxvt urxvt256c uxterm xterm gnome-terminal
do
  if [[ -n $(which $terminal 2>/dev/null) ]]
  then
    exec $terminal
    exit
  fi
done

i3-nagbar -m "Could not find a terminal terminal emulator."
