#!/bin/bash

ELEMENTS=()

add_element()
{
  ELEMENTS+=("$1")
}

# Data/Time
add_element "$(date +'%a %B %d %R')"

# User@Host
add_element "$(whoami)@$(hostname)"

# System
add_element "$(uname -sr)"

# Volume
if [[ -n $(which amixer 2>/dev/null) ]]
then
  add_element "♪ $(printf '%4s' "$(amixer get Master | grep -o '\[.*%\]' | head -n 1 | sed 's/\[//g' | sed 's/\]//g')")"
fi

# Title
if [[ -n $(which xtitle 2>/dev/null) ]]
then
  add_element "$(xtitle | awk 'length>48{$0=substr($0,0,49)"..."}1')"
fi

for((i = ${#ELEMENTS[@]} - 1; i >= 0; i--))
do
  element=${ELEMENTS[$i]}
  if [[ ${#element} -gt 0 ]]
  then
    echo -ne "$element" | sed "s/\&/\&amp;/g"
    if [[ $i != 0 ]]
    then
      echo -ne " • "
    fi
  fi
done
