#!/bin/bash

if [[ -n $(which scrot 2>/dev/null) && -n $(which convert 2>/dev/null) && -n $(which amixer 2>/dev/null) ]]
then
  IMAGE=/tmp/i3lock.png
  ICON=~/.i3/i3lock-icon.png
  SOUND=$(amixer sget Master | grep -E -o '\[on\]')
  scrot $IMAGE
  convert $IMAGE -scale 10% -scale 1000% $IMAGE
  convert $IMAGE $ICON -gravity center -composite -matte $IMAGE
  amixer -q set Master mute
  i3lock -e -n -u -i $IMAGE &
  wait
  if [[ $SOUND == "[on]" ]]
  then
    amixer -q set Master unmute
  fi
  rm $IMAGE
else
  i3lock -c 000000
fi
