#!/bin/sh
set -o errexit
set -o nounset

DIR="$(dirname "$(readlink -f "$0")")/../.."

if [ -s "$DIR"/test/tmp/cat ]
then
  printf "%s" "$(/usr/bin/cat "$DIR"/test/tmp/cat)"
else
  # shellcheck disable=SC2068
  /usr/bin/cat $@
fi