#!/bin/bash

# Allow alias expansion with sudo
alias sudo="sudo "

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../../"
alias ......="cd ../../../../../../"

# grep
alias grep="grep -i --color=auto"

# ls
alias l="ls"
alias ls="ls -h --color=auto"
alias la="ls -a"
alias ll="ls -l"

# path
alias path='echo $PATH | tr -s ":" "\n"'

# docker
alias d="docker"
alias dc="docker-compose"

# git
alias g="git"

# tmux
alias t="tmux"
alias tmux="tmux -2"

# vim
alias v="vi"
if [[ -x $(which nvim 2>/dev/null) ]]; then
  alias vi="nvim"
elif [[ -x $(which vim 2>/dev/null) ]]; then
  alias vi="vim"
fi
