# Hyprland configuration
source = ~/.config/hypr/scripts/../conf/monitors.conf
source = ~/.config/hypr/scripts/../conf/env.conf
source = ~/.config/hypr/scripts/../conf/input.conf
source = ~/.config/hypr/scripts/../conf/appearance.conf
source = ~/.config/hypr/scripts/../conf/autostart.conf
source = ~/.config/hypr/scripts/../conf/binds.conf
source = ~/.config/hypr/scripts/../conf/rules.conf
