# Hyprlock — screen locker for Hyprland

auth {
    pam:module = hyprlock-custom
}

background {
    monitor =
    path = ~/.config/wallpaper/default.png
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    brightness = 0.6
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(61afef)
    inner_color = rgb(121212)
    font_color = rgb(d0d0d0)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 0
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(d0d0d0)
    font_size = 48
    font_family = Source Code Pro
    position = 0, 80
    halign = center
    valign = center
}
