# Hyprland configuration
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/rules.conf
