# Systemd user and system units to enable and start
# Each section is a category conjunction

[linux]
units = [
  "clean-home-tmp.timer",
]

[arch-desktop]
units = [
  { name = "NetworkManager.service", scope = "system" },
  { name = "dhcpcd.service", scope = "system", enabled = false },
  "clean-screenshots.timer",
  "dotfiles-first-login.service",
  "fullscreen-waybar.service",
  "gammastep.service",
  "gnome-keyring-daemon.socket",
  "hypridle.service",
  "hyprpaper.service",
  "mako.service",
  { name = "network-manager-applet.service", scope = "user", enabled = false },
  "volume.service",
  "waybar.service",
  "waybar-workspaces.service",
]
