#!/usr/bin/env zsh

# Remove docker images and containers

command -v docker >/dev/null 2>&1 || { echo "ERROR: docker not installed" 1>&2 && return 1; }

# Remove stopped containers
docker container prune -f

# Remove unused networks
docker network prune -f

# Remove dangling images
docker image prune -f
