#!/usr/bin/env zsh
# shellcheck shell=bash  # Closest to zsh for shellcheck purposes

# Find file

command -v fzf >/dev/null 2>&1 || { echo "ERROR: fzf not installed" 1>&2 && return 1; }
command -v "${EDITOR:-vim}" >/dev/null 2>&1 || { echo "ERROR: ${EDITOR:-vim} not installed" 1>&2 && return 1; }

if ! command -v locate >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
  echo "ERROR: neither locate nor fd installed" 1>&2
  return 1
fi

local opts edit query file
opts=$(getopt -o e -n ff -- "$@") || return 1
eval set -- "$opts"

while [ $# -gt 0 ]
do
  case "$1" in
    -e)
      edit=true
      ;;
    --)
      query="$2"
      ;;
  esac
  shift
done

if [ -z "$query" ]
then
  echo "Usage: ff <file> [<options>]"
  echo
  echo "Options:"
  echo
  echo " -e :  Edit the file"
  return 1
fi

if command -v fd >/dev/null 2>&1; then
  file="$(fd --type f "$query" | fzf -0 -1)" || return 1
else
  file="$(locate "$query" | fzf -0 -1)" || return 1
fi

if [ -z "$file" ]; then
  return 1
fi

if [ -z "$edit" ]
then
  echo "$file"
elif [ -f "$file" ]
then
  if [ -w "$file" ]
  then
    ${EDITOR:-vim} "$file"
  elif command -v sudo >/dev/null 2>&1
  then
    sudo -e "$file"
  else
    echo "ERROR: $file is not writable and sudo is not installed" 1>&2
    return 1
  fi
else
  return 1
fi

