#!/usr/bin/env zsh

# Generate ssh key for GitHub

[ -n "$(command -v git)"        ] || { echo "ERROR: git not installed"        1>&2 && return 1; }
[ -n "$(command -v ssh-keygen)" ] || { echo "ERROR: ssh-keygen not installed" 1>&2 && return 1; }

mkdir -p -m 700 "$HOME"/.ssh/github

if [ -f "$HOME/.ssh/github/id_ed25519" ]; then
  echo "Key already exists: $HOME/.ssh/github/id_ed25519"
  return 1
fi

ssh-keygen -t ed25519 -C "$(git config --global user.email)" -f "$HOME"/.ssh/github/id_ed25519
