#!/usr/bin/env zsh

# Update mirrorlist using reflector (modern replacement for rankmirrors)

[ -n "$(command -vp reflector)" ] || { echo "ERROR: reflector not installed" 1>&2 && return 1; }

sudo reflector --country US --protocol https --latest 6 --sort rate --save /etc/pacman.d/mirrorlist
