#!/usr/bin/env zsh

# Update mirrorlist

[ -n "$(command -vp rankmirrors)" ] || { echo "ERROR: rankmirrors not installed" 1>&2 && return 1; }

sudo sh -c "curl -sL 'https://www.archlinux.org/mirrorlist/?country=US&protocol=https&ip_version=4' | sed 's/^#Server/Server/' | rankmirrors -n 6 - > /etc/pacman.d/mirrorlist"
