#!/bin/bash

# Allow alias expansion with sudo
alias sudo="sudo "

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../../"
alias ......="cd ../../../../../../"

# grep
alias grep="grep -i --color=auto"

# ls
alias l="ls"
alias ls="ls -h --color=auto"
alias la="ls -a"
alias ll="ls -l"

# path
alias path='echo $PATH | tr -s ":" "\n"'

# tmux
alias tmux="tmux -2"

# vim
if [[ -n $(command -v nvim) ]]
then
  alias vi="nvim"
elif [[ -n $(command -v vim) ]]
then
  alias vi="vim"
fi
