#!/usr/bin/env zsh

# Remove docker images and containers

[ -n "$(command -vp docker)" ] || { echo "ERROR: docker not installed" 1>&2 && return 1; }

# Remove stopped containers
docker container prune -f

# Remove dangling images
docker image prune -f
