#!/usr/bin/env zsh

# Extract archives

if [ -z "$1" ]; then
  echo "Usage: extract <file>"
  return 1
fi

if [ ! -f "$1" ]; then
  echo "'$1' is not a valid file" 1>&2
  return 1
fi

case "$1" in
  *.tar.bz2|*.tbz2|*.tar.gz|*.tgz|*.tar.xz|*.txz|*.tar.Z|*.tar|*.tar.zst|*.tzst) tar xf "$1" ;;
  *.bz2)            bunzip2 "$1" ;;
  *.gz)             gunzip  "$1" ;;
  *.rar)            unrar x "$1" ;;
  *.zip)            unzip   "$1" ;;
  *.7z)             7z x    "$1" ;;
  *.Z)              uncompress "$1" ;;
  *.xz)             unxz    "$1" ;;
  *)                echo "'$1' cannot be extracted via extract()" 1>&2; return 1 ;;
esac
