#!/usr/bin/env zsh

# Find file

# shellcheck disable=SC2168,SC2155

[ -n "$(command -vp fzf)"    ] || { echo "ERROR: fzf not installed"    1>&2 && return 1; }
[ -n "$(command -vp sudo)"   ] || { echo "ERROR: sudo not installed"   1>&2 && return 1; }
[ -n "$(command -vp vim)"    ] || { echo "ERROR: vim not installed"    1>&2 && return 1; }

if ! command -v locate >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
  echo "ERROR: neither locate nor fd installed" 1>&2
  return 1
fi

local opts=$(getopt -o e -n ff -- "$@") || return 1
eval set -- "$opts"

while [ $# -gt 0 ]
do
  case "$1" in
    -e)
      local edit=true
      ;;
    --)
      local query="$2"
      ;;
  esac
  shift
done

if [ -z "$query" ]
then
  echo "Usage: ff <file> [<options>]"
  echo
  echo "Options:"
  echo
  echo " -e :  Edit the file"
  return 1
fi

if command -v fd >/dev/null 2>&1; then
  file="$(fd --type f "$query" | fzf -0 -1)" || return 1
else
  file="$(locate "$query" | fzf -0 -1)" || return 1
fi

if [ -z "$file" ]; then
  return 1
fi

if [ -z "$edit" ]
then
  echo "$file"
elif [ -f "$file" ]
then
  if [ -w "$file" ]
  then
    vim "$file"
  else
    sudo -e "$file"
  fi
else
  return 1
fi

