#!/usr/bin/env zsh

# Generate ssh key for GitHub

[ -n "$(command -vp git)"        ] || { echo "ERROR: git not installed"        1>&2 && return 1; }
[ -n "$(command -vp ssh-keygen)" ] || { echo "ERROR: ssh-keygen not installed" 1>&2 && return 1; }

mkdir -p "$HOME"/.ssh/github
ssh-keygen -t ed25519 -C "$(git config --global user.email)" -f "$HOME"/.ssh/github/id_ed25519
