#!/usr/bin/env bash

# Guard against multiple sourcing
[ -n "$BASH_PROFILE_LOADED" ] && return
BASH_PROFILE_LOADED=1

# Profile
# shellcheck disable=SC1090
[ -r ~/.config/shell/profile.sh ] && . ~/.config/shell/profile.sh

# GUI Profile (optional)
# shellcheck disable=SC1090
[ -r ~/.config/shell/profile-desktop.sh ] && . ~/.config/shell/profile-desktop.sh

# GUI Arch Profile (optional)
# shellcheck disable=SC1090
[ -r ~/.config/shell/profile-arch-desktop.sh ] && . ~/.config/shell/profile-arch-desktop.sh

# Interactive shell configuration
if [[ $- == *i* ]]; then
  # shellcheck disable=SC1090
  [ -r ~/.bashrc ] && . ~/.bashrc
fi
