#!/usr/bin/env bash
# shellcheck shell=bash

# History
mkdir -p ~/.cache/bash
export HISTFILE=~/.cache/bash/history
export HISTSIZE=10000
export HISTFILESIZE=10000
shopt -s histappend
shopt -s checkwinsize

# Path
. ~/.config/shell/path.sh

# Aliases
. ~/.config/shell/aliases.sh

# GUI Aliases
[ -f ~/.config/shell/aliases-desktop.sh ] && . ~/.config/shell/aliases-desktop.sh

# Prompt
. ~/.config/bash/prompt

# zoxide
if command -v zoxide >/dev/null 2>&1
then
  eval "$(zoxide init bash)"
fi
