#!/usr/bin/env bash
# shellcheck shell=bash

# Guard against multiple sourcing
[ -n "$BASHRC_LOADED" ] && return
BASHRC_LOADED=1

# History
[ -d ~/.cache/bash ] || mkdir -p ~/.cache/bash
export HISTFILE=~/.cache/bash/history
export HISTSIZE=10000
export HISTFILESIZE=10000
shopt -s histappend
shopt -s checkwinsize

# Path
[ -r ~/.config/shell/path.sh ] && . ~/.config/shell/path.sh

# Aliases
[ -r ~/.config/shell/aliases.sh ] && . ~/.config/shell/aliases.sh

# GUI Aliases (optional)
[ -r ~/.config/shell/aliases-desktop.sh ] && . ~/.config/shell/aliases-desktop.sh

# Prompt
[ -r ~/.config/bash/prompt ] && . ~/.config/bash/prompt

# zoxide
if command -v zoxide >/dev/null 2>&1
then
  eval "$(zoxide init bash)"
fi
