#!/bin/sh

if [ -d "/etc/X11/xinit/xinitrc.d" ]
then
  for f in /etc/X11/xinit/xinitrc.d/*
  do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# preferences
[ -f "$HOME/.Xresources" ] && xrdb "$HOME/.Xresources"
xset s off
xset -dpms
xset s noblank

# xsession.target
if [ -f /etc/X11/xinit/xinitrc.d/50-systemd-user.sh ] && [ -n "$(command -vp systemctl)" ]
then
  /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
  systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
  systemctl --no-block --user start xsession.target
fi

# xmonad
if [ -n "$(command -vp xmonad)" ]
then
  exec xmonad
fi
