#!/usr/bin/env zsh

# Guard against multiple sourcing
[ -n "$ZPROFILE_LOADED" ] && return
ZPROFILE_LOADED=1

# Start graphical session on tty1 if not already in one
if [ -z "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
    exec "$HOME/.local/bin/start-session"
fi
