#!/usr/bin/env zsh

# Remove docker images and containers

[ -n "$(command -vp docker)" ] || { echo "ERROR: docker not installed" 1>&2 && return 1; }

docker rm "$(docker ps -qa)" 2>/dev/null
docker rmi "$(docker images -qa)" 2>/dev/null
