#!/usr/bin/env zsh

# Locate and edit a file

[ -n "$(command -vp fzf)"    ] || { echo "ERROR: fzf not installed"    1>&2 && return 1; }
[ -n "$(command -vp locate)" ] || { echo "ERROR: locate not installed" 1>&2 && return 1; }
[ -n "$(command -vp sudo)"   ] || { echo "ERROR: sudo not installed"   1>&2 && return 1; }
[ -n "$(command -vp vim)"    ] || { echo "ERROR: vim not installed"    1>&2 && return 1; }

if [ -z "$1" ]
then
  echo "Usage: eloc <file>"
  return 1
fi

files=$(locate "$1") || return 1
file="$(echo "$files" | fzf)" || return 1
if [ -f "$file" ]
then
  if [ -w "$file" ]
  then
    vim "$file"
  else
    sudo -k -e "$file"
  fi
else
  return 1
fi
