" Preamble {{{

" Nocompatible
set nocompatible

" Leader key
let mapleader=','

" Filetype indent
filetype plugin indent on

" }}}

" Vim-Plug {{{

source ~/.vim/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')

" Plugins
Plug 'bling/vim-airline', { 'tag': 'v0.7' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'junegunn/vim-easy-align'
Plug 'kien/ctrlp.vim'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'sirver/ultisnips'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'

" Color scheme
Plug 'nanotech/jellybeans.vim', { 'tag': 'v1.5' }

" Syntax
Plug 'hdima/python-syntax', { 'for': 'python' }
Plug 'jelera/vim-javascript-syntax', { 'for': 'javascript' }
Plug 'octol/vim-cpp-enhanced-highlight', { 'for': ['c', 'cpp'] }
Plug 'raichoo/haskell-vim', { 'for': 'haskell' }
Plug 'stanangeloff/php.vim', { 'for': 'php' }

call plug#end()

" }}}

" General {{{

" Basic options {{{

set autoindent
set backspace=2
set cindent
set cmdheight=1
set copyindent
set encoding=utf-8
set expandtab
set fileformats=unix,dos,mac
set formatoptions=tcqr
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set list
set listchars=tab:▸\ ,trail:·
set mouse=a
set nobackup
set noerrorbells
set nonumber
set noswapfile
set pastetoggle=<f10>
set preserveindent
set ruler
set scrolloff=5
set shiftwidth=2
set showmatch
set showmode
set smartcase
set smartindent
set softtabstop=2
set splitbelow
set splitright
set tabstop=2
set textwidth=0
set ttyfast
set viminfo=
set wildmenu
set wrap
set wrapscan

" }}}

" Color scheme {{{

syntax on
set t_Co=256

try
  colorscheme jellybeans

  " Match the background color for special keys
  highlight SpecialKey ctermbg=233
catch
  colorscheme default
endtry

" }}}

" Wildignore {{{

set wildignore+=*.bmp
set wildignore+=*.ddl
set wildignore+=*.exe
set wildignore+=*.gif
set wildignore+=*.jpeg
set wildignore+=*.jpg
set wildignore+=*.min.*
set wildignore+=*.o
set wildignore+=*.png
set wildignore+=*.so
set wildignore+=*.swp
set wildignore+=*.zip

set wildignore+=*/.git/*
set wildignore+=*/.hg/*
set wildignore+=*/.svn/*
set wildignore+=*/__pycache__/*
set wildignore+=*/bower_components/*
set wildignore+=*/node_modules/*

" }}}

" Buffers {{{

" Keep splits equally sized
autocmd VimResized * :wincmd =

" Make the quickfix window span the bottom of the screen
autocmd FileType qf :wincmd J

" Close vim if a quickfix window is the only remaining buffer
autocmd WinEnter * if winnr('$') == 1 && getbufvar(winbufnr(winnr()), '&buftype') == 'quickfix'|q|endif

" }}}

" Whitespace {{{

" Strip trailing whitespace from every line on save
function! StripTrailingWhitespaces() " {{{
  let _s=@/
  let l = line('.')
  let c = col('.')
  %s/\s\+$//e
  let @/=_s
  call cursor(l, c)
endfunction " }}}
autocmd BufWritePre * call StripTrailingWhitespaces()

" }}}

" Folding {{{

" Toggle fold
nnoremap <leader><return> za

" Focus the current fold
noremap <leader>z zMzvzz

set foldmethod=marker
set foldtext=FoldText()
function! FoldText() " {{{
  let line = getline(v:foldstart)
  let nucolwidth = &fdc + &number * &numberwidth
  let windowwidth = winwidth(0) - nucolwidth - 1
  let foldedlinecount = v:foldend - v:foldstart
  let onetab = strpart('          ', 0, &tabstop)
  let line = substitute(line, '\t', onetab, 'g')
  let line = strpart(line, 0, windowwidth - 2 - len(foldedlinecount))
  let fillcharcount = windowwidth - len(line) - len(foldedlinecount)
  return line . repeat(' ', fillcharcount) . foldedlinecount . ' '
endfunction " }}}

" }}}

" }}}

" Mappings {{{

noremap ; :
noremap j gj
noremap k gk
noremap * *<c-o>
noremap / /\v
noremap ? ?\v
noremap H 0
noremap L $
noremap <tab> %

" Disable keys
noremap <up>     <nop>
noremap <down>   <nop>
noremap <left>   <nop>
noremap <right>  <nop>
noremap <home>   <nop>
noremap <end>    <nop>
noremap <insert> <nop>
noremap <del>    <nop>

" Center search results while navigating
nnoremap n nzzzv
nnoremap N Nzzzv

" Toggle spell check
noremap K :set spell! spelllang=en_us<cr>

" Clear all highlights
noremap <space> :noh<cr>

" Tabs
noremap <c-r>n :tabnew<cr>
noremap <c-r><c-r> :tabnext<cr>
noremap <c-r>1 1gt
noremap <c-r>2 2gt
noremap <c-r>3 3gt
noremap <c-r>4 4gt
noremap <c-r>5 5gt
noremap <c-r>6 6gt
noremap <c-r>7 7gt
noremap <c-r>8 8gt
noremap <c-r>9 9gt

" Open .vimrc
noremap <leader>v :e ~/.vim/vimrc<cr>

" Execute the current file
noremap <leader>e :!%:p<cr>

" Toggle line wrap
noremap <leader>w :set wrap!<cr>

" Search and replace the word under the cursor
noremap <leader>r :%s/\<<c-r><c-w>\>//g<left><left>

" Search for a string in the current directory
noremap <leader>g :vimgrep //j ** <bar> cw<left><left><left><left><left><left><left><left><left><left>

" <C-h> fix
nmap <BS> <C-W>h
if has('nvim')
  nmap <bs> :<c-u>TmuxNavigateLeft<cr>
endif

" }}}

" Filetype {{{

" C++ {{{

" Indentation
autocmd Filetype c,cpp setlocal sw=4 ts=4 sts=4

" }}}

" Java {{{

" Indentation
autocmd Filetype java setlocal sw=4 ts=4 sts=4

" }}}

" Python {{{

" Indentation
autocmd Filetype python setlocal sw=4 ts=4 sts=4

" }}}

"}}}

" Plugins {{{

" Airline {{{

let g:airline_left_sep=''
let g:airline_left_alt_sep=''
let g:airline_right_sep=''
let g:airline_right_alt_sep=''

let g:airline#extensions#default#layout=[[ 'a', 'b', 'c' ], [ 'x', 'z', 'warning' ]]

let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#show_buffers=0
let g:airline#extensions#tabline#tab_min_count=2
let g:airline#extensions#tabline#tab_nr_type=1
let g:airline#extensions#tabline#left_sep=''
let g:airline#extensions#tabline#left_alt_sep=''
let g:airline#extensions#tabline#right_sep=''
let g:airline#extensions#tabline#right_alt_sep=''
let g:airline#extensions#tabline#fnamemod=':t'

let g:airline#extensions#whitespace#enabled=0

let g:tmuxline_separators={ 'left': '', 'left_alt': '', 'right': '', 'right_alt': '', 'space': ' ' }

if ! has('gui_running')
  set ttimeoutlen=10
  augroup FastEscape
    autocmd!
    au InsertEnter * set timeoutlen=0
    au InsertLeave * set timeoutlen=1000
  augroup END
endif

" }}}

" Ctrl-P {{{

let g:ctrlp_map='<c-p>'
let g:ctrlp_cmd='CtrlP'
let g:ctrlp_switch_buffer='e'
let g:ctrlp_working_path_mode='ra'

" }}}

" Dispatch {{{

" Map the default make command to the command provided by dispatch
cnoreabbrev <expr> make ((getcmdtype() == ':' && getcmdpos() <= 5) ? 'Make': 'make')

" }}}

" Easy align {{{

" Start interactive EasyAlign in visual mode
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object
nmap ga <Plug>(EasyAlign)

" }}}

" Nerdtree {{{

let NERDTreeMinimalUI=1
let NERDTreeShowHidden=1
let NERDTreeRespectWildIgnore=1
let NERDTreeWinPos="right"
noremap <silent><c-e> :NERDTreeToggle<cr>:wincmd =<cr>

" Auto close vim if Nerd tree is the only remaining buffer
function! CloseIfOnlyNerdTreeLeft() " {{{
  if exists('t:NERDTreeBufName')
    if bufwinnr(t:NERDTreeBufName) != -1
      if winnr('$') == 1
        q
      endif
    endif
  endif
endfunction " }}}
autocmd WinEnter * call CloseIfOnlyNerdTreeLeft()

" }}}

" Python syntax {{{

let g:python_highlight_builtin_funcs=1
let g:python_highlight_builtin_objs=1
let g:python_highlight_exceptions=1
let g:python_highlight_file_headers_as_comments=1

" }}}

" UltiSnips {{{

" Disable python warning
let g:UltiSnipsNoPythonWarning=1

" Edid snips in horizontal split
let g:UltiSnipsEditSplit="horizontal"

" }}}

" }}}
