//! Task: install AI plugin manifests via Microsoft APM.
//!
//! See <https://github.com/microsoft/apm>.  The dotfiles repo ships an
//! `apm/config/base.yml` under `symlinks/` which is linked to
//! `~/.apm/config/base.yml` by the
//! [`InstallSymlinks`](crate::tasks::files::symlinks::InstallSymlinks) task.  Overlay
//! repositories may symlink additional fragments into `~/.apm/config/*.yml`
//! (for example `~/.apm/config/work.yml`).
//!
//! Because `apm install -g --target ...` always reads the manifest at
//! `~/.apm/apm.yml` regardless of cwd, this task merges every
//! `~/.apm/config/*.yml` fragment into a single generated `~/.apm/apm.yml`.
//! It then invokes `apm install -g --target copilot` plus `copilot-app` when the
//! Copilot App database is present, whenever install state must be materialized,
//! including ordinary up-to-date runs so local symlinked plugin edits are
//! redeployed to their real runtime locations.
//! Idempotency is provided by APM itself via its lockfile; the merged file is
//! regenerated deterministically every run.
//!
//! Advancing locked dependency refs (`apm outdated` followed by `apm update`)
//! is **not** part of this task.  It is handled separately
//! by [`UpdateApmPackages`], which runs in [`TaskPhase::Update`] and is only
//! scheduled by the `update` command (when `ctx.advance_versions` is set).
//! The `install` command therefore converges to the declared/locked manifest
//! without moving any locked ref forward, and shows no `Updating dependencies`
//! phase.  See [`advance_apm_dependencies`].
//!
//! The experimental `copilot-app` target integrates hand-authored Copilot App
//! workflow prompts (`.prompt.md` files carrying workflow frontmatter) into
//! `~/.copilot`.  It is gated behind apm's experimental flag, persisted in the
//! machine-local `~/.apm/config.json`, so this task first runs the idempotent
//! `apm experimental enable copilot-app` (see `ensure_copilot_app_enabled`) to
//! keep fresh machines reproducible.  That step is best-effort: an older apm
//! without the subcommand simply logs a warning and the non-experimental
//! targets still install.
//!
//! The `copilot-app` target only meaningfully encodes `.prompt.md` fragments
//! with workflow frontmatter (under the `apm--` id namespace).  In apm 0.16.x,
//! however, it also walks other deployed primitives and refuses to
//! lockfile-encode any whose id is outside that namespace -- notably the
//! `.agent.md` agent files shipped by third-party packages -- which makes
//! `apm install` exit non-zero even though the `copilot`/`vscode` targets
//! deployed those agents correctly.  Because that failure is a benign,
//! upstream-only limitation of the experimental target,
//! [`run_apm_install`] tolerates it when (and only when) every reported error
//! is that specific encoding failure; any other error still fails the task.
//! See [`tolerable_workflow_encode_failures`].

use anyhow::{Context as _, Result};
use std::path::{Path, PathBuf};

use crate::tasks::{Context, Domain, Task, TaskPhase, TaskResult, task_deps};

mod autopilot;
mod fragments;
mod manifest;
mod outdated;

use autopilot::{apply_workflow_autopilot_fixup, snapshot_desired_apm_workflow_ids};
use fragments::{discover_fragment_files, discover_yaml_files, merge_fragments};
use manifest::{
    describe_dependencies, manifest_fingerprint, manifest_marker_matches,
    merged_manifest_needs_write, write_manifest_marker, write_merged_manifest,
};
use outdated::{ApmOutdatedCheck, ApmUpdateOutcome, outdated_output_has_updates};

/// Header written at the top of the generated `~/.apm/apm.yml`.  The contents
/// are not meaningful to APM itself beyond providing a valid manifest, but
/// the warning helps anyone who opens the file by hand.
const GENERATED_HEADER: &str =
    "# Generated by dotfiles from ~/.apm/config/*.yml fragments.\n# Manual edits will be lost.\n";
const APM_COPILOT_TARGET: &str = "copilot";
const APM_COPILOT_APP_TARGETS: &str = "copilot,copilot-app";
const APM_NONINTERACTIVE_ENV: &[(&str, &str)] = &[
    ("GIT_TERMINAL_PROMPT", "0"),
    ("GCM_INTERACTIVE", "Never"),
    ("GCM_GUI_PROMPT", "false"),
];
const APM_UP_TO_DATE_MARKER: &str = "all dependencies are up-to-date";
/// Per-package failure record emitted by the experimental `copilot-app` target
/// when it refuses to lockfile-encode a deployed primitive whose id is outside
/// apm's `apm--<owner>--<pkg>--<prompt>` workflow namespace.
///
/// This happens for `.agent.md` agent files shipped by third-party packages:
/// the `copilot` target still deploys those agents correctly, so the failure is
/// a benign, upstream-only limitation of the experimental target. APM has
/// changed the prefix for this diagnostic across releases, so match the stable
/// refusal text and still fail closed unless the count equals APM's error total.
const APM_WORKFLOW_ENCODE_FAILURE_MARKER: &str = "Refusing to lockfile-encode non-APM workflow id";

/// APM targets that are safe to materialize for the current user profile.
#[derive(Debug, Clone, Copy)]
struct ApmTargets {
    include_copilot_app: bool,
}

impl ApmTargets {
    /// Detect whether the Copilot App target should be included.
    ///
    /// # Errors
    ///
    /// Returns an error when the Copilot App database path cannot be probed.
    fn detect(ctx: &Context) -> Result<Self> {
        let db_path = copilot_app_db_path(ctx);
        let include_copilot_app = db_path
            .try_exists()
            .with_context(|| format!("checking Copilot App database {}", db_path.display()))?;
        if !include_copilot_app {
            ctx.debug_fmt(|| {
                format!(
                    "omitting apm target copilot-app because {} is missing",
                    db_path.display()
                )
            });
        }
        Ok(Self {
            include_copilot_app,
        })
    }

    #[must_use]
    const fn as_str(self) -> &'static str {
        if self.include_copilot_app {
            APM_COPILOT_APP_TARGETS
        } else {
            APM_COPILOT_TARGET
        }
    }

    #[must_use]
    const fn includes_copilot_app(self) -> bool {
        self.include_copilot_app
    }

    #[must_use]
    const fn install_args(self) -> [&'static str; 4] {
        ["install", "-g", "--target", self.as_str()]
    }

    #[must_use]
    const fn update_args(self) -> [&'static str; 5] {
        ["update", "-g", "--yes", "--target", self.as_str()]
    }
}

/// Return the user-scope Copilot App database path used by APM.
fn copilot_app_db_path(ctx: &Context) -> PathBuf {
    ctx.home.join(".copilot").join("data.db")
}

/// Return a platform-specific reason for skipping APM work when `apm` is absent.
fn missing_apm_reason(ctx: &Context) -> String {
    let hint = if ctx.platform.is_wsl() {
        Some(
            "install the Windows package with `winget.exe install Microsoft.APM` and re-open your \
             WSL shell",
        )
    } else if ctx.platform.is_windows() {
        Some("install it with `winget install Microsoft.APM`")
    } else if ctx.platform.supports_aur() {
        Some("install it with `paru -S apm-bin`")
    } else {
        None
    };
    hint.map_or_else(
        || "apm not found in PATH".to_string(),
        |hint| format!("apm not found in PATH; {hint}"),
    )
}

/// Converge AI plugin manifests via Microsoft APM.
///
/// Merges the manifest fragments and runs `apm install`, redeploying locally
/// symlinked plugin edits.  It never advances locked dependency refs — that is
/// [`UpdateApmPackages`]'s job under the `update` command.
#[derive(Debug)]
pub struct InstallApmPackages;

impl Task for InstallApmPackages {
    fn name(&self) -> &'static str {
        "Install APM packages"
    }

    fn phase(&self) -> TaskPhase {
        TaskPhase::Provision
    }

    fn domain(&self) -> Domain {
        Domain::Ai
    }

    task_deps![
        crate::tasks::packages::InstallPackages,
        crate::tasks::packages::InstallAurPackages,
        crate::tasks::files::symlinks::InstallSymlinks
    ];

    fn should_run(&self, ctx: &Context) -> bool {
        apm_task_should_run(ctx)
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        if !ctx.dry_run && !ctx.executor.which("apm") {
            let reason = missing_apm_reason(ctx);
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let fragments = discover_fragment_files(&ctx.home)?;
        if fragments.is_empty() {
            let reason = "no manifest fragments found under ~/.apm/config/".to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let manifest_path = ctx.home.join(".apm").join("apm.yml");
        let lock_path = ctx.home.join(".apm").join("apm.lock.yaml");
        let marker_path = ctx.home.join(".apm").join(".dotfiles-manifest.sha256");
        let merged = merge_fragments(&fragments)?;
        let manifest_hash = manifest_fingerprint(&merged);
        let state = ApmInstallState::detect(
            &manifest_path,
            &lock_path,
            &marker_path,
            &merged,
            &manifest_hash,
        )?;
        let targets = ApmTargets::detect(ctx)?;

        if ctx.dry_run {
            if targets.includes_copilot_app() {
                ctx.log
                    .dry_run("run apm experimental enable copilot-app (idempotent) before install");
                ctx.log.dry_run(
                    "re-assert apm-managed Copilot App workflows to autopilot + enabled in \
                     ~/.copilot/data.db after a successful install",
                );
            }
            if state.manifest_needs_write {
                ctx.log.dry_run(&format!(
                    "merge {} APM manifest fragment(s) into {}",
                    fragments.len(),
                    manifest_path.display()
                ));
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {} to sync changed manifest",
                    targets.as_str()
                ));
            } else if state.lock_missing {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {} because {} is missing",
                    targets.as_str(),
                    lock_path.display()
                ));
            } else if state.marker_missing_or_stale {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {} because the current manifest has \
                     not been installed successfully yet",
                    targets.as_str()
                ));
            } else {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {} to redeploy current manifest content",
                    targets.as_str()
                ));
            }
            return Ok(TaskResult::DryRun);
        }

        let pre_workflows = targets
            .includes_copilot_app()
            .then(|| snapshot_desired_apm_workflow_ids(ctx));
        if targets.includes_copilot_app() {
            ensure_copilot_app_enabled(ctx);
        }

        let manifest_changed = state.manifest_changed();
        if state.manifest_needs_write {
            write_merged_manifest(&manifest_path, &merged)?;
        }

        // Always (re)run `apm install` so locally symlinked plugin edits are
        // redeployed to their runtime locations.  When the manifest changed
        // this also installs newly declared dependencies; on an unchanged
        // manifest it is a quiet idempotent redeploy.
        let install_result = run_apm_install(ctx, targets)?;
        if !matches!(install_result, TaskResult::Ok) {
            // Auth skip (or similar): do not record the manifest as installed
            // and do not attempt to advance dependencies.
            return Ok(install_result);
        }
        if manifest_changed {
            ctx.log
                .always(&format!("    install: {}", describe_dependencies(&merged)));
        }
        write_manifest_marker(&marker_path, &manifest_hash)?;

        // Convergence is complete.  Advancing locked dependency refs
        // (`apm outdated` / `apm update`) is a separate concern handled by
        // the `update`-only [`UpdateApmPackages`] task in [`TaskPhase::Update`],
        // so this task never moves a locked ref forward.
        if let Some(pre) = pre_workflows {
            apply_workflow_autopilot_fixup(ctx, &pre);
        }
        Ok(TaskResult::Ok)
    }
}

/// Filesystem-derived signals that decide whether `apm install` must run and
/// what to report.
///
/// Computed once per [`InstallApmPackages::run`] from the merged manifest and
/// the on-disk lockfile/marker so the dry-run preview and the real execution
/// path branch on identical state.
#[derive(Debug, Clone, Copy)]
struct ApmInstallState {
    /// The merged manifest differs from the on-disk `~/.apm/apm.yml`.
    manifest_needs_write: bool,
    /// The APM lockfile is absent (a fresh machine or wiped state).
    lock_missing: bool,
    /// The success marker is missing or does not match the current manifest.
    marker_missing_or_stale: bool,
}

impl ApmInstallState {
    /// Detect install state from the merged manifest and on-disk artifacts.
    ///
    /// # Errors
    ///
    /// Propagates IO errors from comparing the merged manifest against the
    /// target, probing the lockfile, or reading the success marker.
    fn detect(
        manifest_path: &Path,
        lock_path: &Path,
        marker_path: &Path,
        merged: &str,
        manifest_hash: &str,
    ) -> Result<Self> {
        let manifest_needs_write = merged_manifest_needs_write(manifest_path, merged)?;
        let lock_missing = !lock_path
            .try_exists()
            .with_context(|| format!("checking APM lockfile {}", lock_path.display()))?;
        let marker_missing_or_stale = !manifest_marker_matches(marker_path, manifest_hash)?;
        Ok(Self {
            manifest_needs_write,
            lock_missing,
            marker_missing_or_stale,
        })
    }

    /// Whether `apm install` will materially change locked or installed state.
    const fn manifest_changed(self) -> bool {
        self.manifest_needs_write || self.lock_missing || self.marker_missing_or_stale
    }
}

/// Whether an APM task should run on this machine.
///
/// True whenever the symlinks layer ships manifest fragments, or whenever
/// fragments have already been linked into `~/.apm/config/`.  Shared by
/// [`InstallApmPackages`] and [`UpdateApmPackages`] so both gate on the same
/// "APM is in play here" signal.
fn apm_task_should_run(ctx: &Context) -> bool {
    let repo_config_dir = ctx
        .config_read()
        .root
        .join("symlinks")
        .join("apm")
        .join("config");
    match discover_yaml_files(&repo_config_dir) {
        Ok(fragments) if !fragments.is_empty() => return true,
        Ok(_) => {}
        Err(err) => {
            ctx.log.warn(&format!(
                "could not inspect symlinks/apm/config; task will run to avoid hiding the \
                 error: {err:#}"
            ));
            return true;
        }
    }

    match discover_fragment_files(&ctx.home) {
        Ok(fragments) => !fragments.is_empty(),
        Err(err) => {
            ctx.log.warn(&format!(
                "could not inspect ~/.apm/config; task will run to surface the error: {err:#}"
            ));
            true
        }
    }
}

/// Advance pinned APM dependency versions — the `update` command only.
///
/// This task runs in [`TaskPhase::Update`], which the scheduler executes after
/// the Provision phase (where [`InstallApmPackages`] has already converged the
/// manifest and lockfile).  It is only ever scheduled when the command sets
/// `ctx.advance_versions` (i.e. `update`, not `install`), so the
/// `:: Updating dependencies` header is absent under ordinary installs.
///
/// Because phases run independently — a failed Provision task does not abort the
/// run before the Update phase — this task re-asserts the convergence
/// precondition itself: it only contacts APM when a current manifest has been
/// installed successfully (lockfile present and the success marker matches the
/// merged manifest hash).  Otherwise it skips, so a half-converged or failed
/// install can never trigger a lockfile-advancing `apm update`.
#[derive(Debug)]
pub struct UpdateApmPackages;

impl Task for UpdateApmPackages {
    fn name(&self) -> &'static str {
        "Update APM packages"
    }

    fn phase(&self) -> TaskPhase {
        TaskPhase::Update
    }

    fn domain(&self) -> Domain {
        Domain::Ai
    }

    fn should_run(&self, ctx: &Context) -> bool {
        apm_task_should_run(ctx)
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        if ctx.dry_run {
            let targets = ApmTargets::detect(ctx)?;
            ctx.log.dry_run(&format!(
                "run apm outdated -g and apm update -g --yes --target {} to advance any stale \
                 dependencies",
                targets.as_str()
            ));
            if targets.includes_copilot_app() {
                ctx.log.dry_run(
                    "re-assert apm-managed Copilot App workflows to autopilot + enabled in \
                     ~/.copilot/data.db after advancing dependencies",
                );
            }
            return Ok(TaskResult::DryRun);
        }

        if !ctx.executor.which("apm") {
            let reason = missing_apm_reason(ctx);
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let fragments = discover_fragment_files(&ctx.home)?;
        if fragments.is_empty() {
            let reason = "no manifest fragments found under ~/.apm/config/".to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        // Re-assert the convergence precondition: only advance locked refs when
        // the current merged manifest has been installed successfully.  This
        // restores the "advance only after a successful install" invariant that
        // the single-task design enforced via early return, now that
        // convergence runs in a separate, independently-failing phase.
        let lock_path = ctx.home.join(".apm").join("apm.lock.yaml");
        let lock_present = lock_path
            .try_exists()
            .with_context(|| format!("checking APM lockfile {}", lock_path.display()))?;
        let merged = merge_fragments(&fragments)?;
        let manifest_hash = manifest_fingerprint(&merged);
        let marker_path = ctx.home.join(".apm").join(".dotfiles-manifest.sha256");
        let marker_matches = manifest_marker_matches(&marker_path, &manifest_hash)?;
        if !lock_present || !marker_matches {
            let reason = "APM manifest has not been installed successfully yet; skipping \
                          dependency advancement"
                .to_string();
            ctx.log.debug(&reason);
            return Ok(TaskResult::Skipped(reason));
        }

        let targets = ApmTargets::detect(ctx)?;
        advance_apm_dependencies(ctx, targets)
    }
}

/// Best-effort enable of the experimental `copilot-app` apm target.
///
/// The `copilot-app` target only encodes workflow prompts once apm's
/// experimental flag is set in the machine-local `~/.apm/config.json`.  Running
/// `apm experimental enable copilot-app` here keeps fresh machines reproducible
/// without a manual step.  The command is idempotent (it reports the flag is
/// already enabled on repeat runs), so it is safe to call on every apply.
///
/// Failure is intentionally non-fatal: an older apm that predates the
/// `experimental` subcommand will error, but the supported `copilot`/`vscode`
/// targets must still install.  Any error is logged as a warning and swallowed.
fn ensure_copilot_app_enabled(ctx: &Context) {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm experimental enable copilot-app` in {} (idempotent)",
            cwd.display()
        )
    });
    match ctx.executor.run_in_with_env(
        &cwd,
        "apm",
        &["experimental", "enable", "copilot-app"],
        APM_NONINTERACTIVE_ENV,
    ) {
        Ok(result) => report_apm_output(ctx, &result.stdout, &result.stderr),
        Err(err) => {
            let msg = format!("{err:#}");
            ctx.log.warn(&format!(
                "could not enable apm experimental copilot-app target; continuing without it \
                 (details: {})",
                msg.trim()
            ));
        }
    }
}

/// Install the current user-scope manifest without refreshing locked refs.
fn run_apm_install(ctx: &Context, targets: ApmTargets) -> Result<TaskResult> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm install -g --target {}` in {} (interactive credential prompts \
             disabled)",
            targets.as_str(),
            cwd.display()
        )
    });
    let args = targets.install_args();
    match ctx
        .executor
        .run_in_with_env(&cwd, "apm", &args, APM_NONINTERACTIVE_ENV)
    {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(TaskResult::Ok)
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm install requires GitHub authentication; run \
                              `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log
                    .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                Ok(TaskResult::Skipped(reason))
            } else if let Some(encode_failures) = targets
                .includes_copilot_app()
                .then(|| tolerable_workflow_encode_failures(&msg))
                .flatten()
            {
                // The experimental `copilot-app` target refused to lockfile-encode
                // `.agent.md` (and other non-workflow) primitives whose ids fall
                // outside apm's `apm--` namespace.  Those primitives are still
                // deployed by the `copilot` target, so the install
                // succeeded for everything that matters.  Route the raw output to
                // the diagnostic log and continue rather than failing the task.
                report_apm_output(ctx, &msg, "");
                ctx.log.warn(&format!(
                    "apm install succeeded; ignoring {encode_failures} experimental \
                     copilot-app workflow-encoding error(s) for non-workflow primitives \
                     (e.g. .agent.md agents). The copilot target deployed normally; \
                     full apm output is in the log."
                ));
                Ok(TaskResult::Ok)
            } else {
                Err(err).context("running apm install")
            }
        }
    }
}

/// Advance locked user-scope dependencies to the latest matching refs.
///
/// Runs only under the `update` command (`ctx.advance_versions`).  Checks
/// `apm outdated -g` first and only runs `apm update --yes` when something is
/// stale.  Returns the resulting task outcome: `Ok` when nothing needed
/// advancing or an update succeeded, or `Skipped` when credentials are
/// unavailable.
///
/// When `apm update` includes the experimental `copilot-app` target, it
/// redeploys workflows secure-by-default (`mode='interactive'`, `enabled=0`),
/// exactly as `apm install` does.  To stop `update` from silently re-disabling
/// the autopilot automations that [`InstallApmPackages`] armed earlier in the
/// run, this snapshots the desired workflows *before* the update and re-asserts
/// autopilot + enabled afterward via [`apply_workflow_autopilot_fixup`].  The
/// fixup is best-effort, idempotent, and stays quiet when no workflow changed
/// state.
fn advance_apm_dependencies(ctx: &Context, targets: ApmTargets) -> Result<TaskResult> {
    Ok(match apm_dependencies_are_outdated(ctx)? {
        ApmOutdatedCheck::Outdated(true) => {
            // Snapshot which dotfiles-managed workflows are already armed before
            // `apm update` redeploys the `copilot-app` target
            // secure-by-default.  `apm outdated` (above) is read-only, so this
            // pre-update state is still intact.
            let pre_workflows = targets
                .includes_copilot_app()
                .then(|| snapshot_desired_apm_workflow_ids(ctx));
            match run_apm_update(ctx, targets)? {
                ApmUpdateOutcome::Changed => {
                    ctx.log.always("    update: advanced to latest versions");
                    // The advance redeployed the workflows disabled; re-arm them.
                    if let Some(pre) = pre_workflows {
                        apply_workflow_autopilot_fixup(ctx, &pre);
                    }
                    TaskResult::Ok
                }
                ApmUpdateOutcome::Unchanged => {
                    ctx.log.debug("APM dependencies already at latest refs");
                    // `apm update` still ran (something looked outdated), so
                    // re-assert autopilot defensively in case it redeployed the
                    // workflows without advancing a ref.  Stays quiet when the
                    // workflows were untouched.
                    if let Some(pre) = pre_workflows {
                        apply_workflow_autopilot_fixup(ctx, &pre);
                    }
                    TaskResult::Ok
                }
                ApmUpdateOutcome::Skipped(reason) => TaskResult::Skipped(reason),
            }
        }
        ApmOutdatedCheck::Outdated(false) => {
            ctx.log.debug("APM dependencies are up-to-date");
            TaskResult::Ok
        }
        ApmOutdatedCheck::Skipped(reason) => TaskResult::Skipped(reason),
    })
}

/// Return whether any locked user-scope dependency has a newer matching ref.
fn apm_dependencies_are_outdated(ctx: &Context) -> Result<ApmOutdatedCheck> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| format!("running `apm outdated -g` in {}", cwd.display()));
    match ctx
        .executor
        .run_in_with_env(&cwd, "apm", &["outdated", "-g"], APM_NONINTERACTIVE_ENV)
    {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(ApmOutdatedCheck::Outdated(outdated_output_has_updates(
                &result.stdout,
                &result.stderr,
            )))
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm outdated requires GitHub authentication; run \
                              `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log.warn(&format!(
                    "skipping APM update check: {reason} (details: {})",
                    msg.trim()
                ));
                Ok(ApmOutdatedCheck::Skipped(reason))
            } else {
                Err(err).context("checking for outdated APM dependencies")
            }
        }
    }
}

/// Refresh locked user-scope dependencies to the latest matching refs.
///
/// Detects whether anything actually advanced by snapshotting the APM lockfile
/// (`~/.apm/apm.lock.yaml`) before and after the run rather than parsing console
/// output.  APM emits no stable "no changes" marker for dependencies pinned to
/// git branch/commit refs — `apm outdated` reports them as `unknown`, so APM
/// re-integrates them on every run even when no ref moves.  The lockfile only
/// changes when a pinned ref actually advances, making it the authoritative
/// change signal.
fn run_apm_update(ctx: &Context, targets: ApmTargets) -> Result<ApmUpdateOutcome> {
    let cwd = ctx.home.clone();
    let lock_path = ctx.home.join(".apm").join("apm.lock.yaml");
    let lock_before = read_lock_snapshot(&lock_path);
    ctx.debug_fmt(|| {
        format!(
            "running `apm update -g --yes --target {}` in {} (interactive credential \
             prompts disabled)",
            targets.as_str(),
            cwd.display()
        )
    });
    let args = targets.update_args();
    match ctx
        .executor
        .run_in_with_env(&cwd, "apm", &args, APM_NONINTERACTIVE_ENV)
    {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            let lock_after = read_lock_snapshot(&lock_path);
            if lock_before == lock_after {
                Ok(ApmUpdateOutcome::Unchanged)
            } else {
                Ok(ApmUpdateOutcome::Changed)
            }
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm update requires GitHub authentication; run \
                                  `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log
                    .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                Ok(ApmUpdateOutcome::Skipped(reason))
            } else if let Some(encode_failures) = targets
                .includes_copilot_app()
                .then(|| tolerable_workflow_encode_failures(&msg))
                .flatten()
            {
                report_apm_output(ctx, &msg, "");
                ctx.log.warn(&format!(
                    "apm update succeeded; ignoring {encode_failures} experimental \
                     copilot-app workflow-encoding error(s) for non-workflow primitives \
                     (e.g. .agent.md agents). The copilot target deployed normally; \
                     full apm output is in the log."
                ));
                let lock_after = read_lock_snapshot(&lock_path);
                if lock_before == lock_after {
                    Ok(ApmUpdateOutcome::Unchanged)
                } else {
                    Ok(ApmUpdateOutcome::Changed)
                }
            } else {
                Err(err).context("updating APM dependencies")
            }
        }
    }
}

/// Read the APM lockfile for before/after change detection.
///
/// A missing lockfile (or any read error) degrades to `None` so update
/// detection never fails the task; an unreadable lockfile that hashes the same
/// way both times simply reports no change.
fn read_lock_snapshot(path: &Path) -> Option<Vec<u8>> {
    std::fs::read(path).ok()
}

/// Relay raw APM command output to the diagnostic log file and the verbose
/// console.
///
/// The headline state-change is emitted separately as an always-visible
/// `    {verb}: {desc}` line by the caller, so this routes APM's own
/// line-by-line chatter through `debug`: it is always captured in the log
/// file and shown under `--verbose`, but stays out of the way on ordinary
/// runs.  APM provides idempotency itself via its lockfile, so this output is
/// purely informational.
fn report_apm_output(ctx: &Context, stdout: &str, stderr: &str) {
    for line in stdout.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.debug(trimmed);
    }
    for line in stderr.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.debug(trimmed);
    }
}

/// Heuristic: does an `apm install` failure message indicate a missing or
/// invalid GitHub credential rather than a real installation error?
fn looks_like_auth_failure(message: &str) -> bool {
    let lowered = message.to_lowercase();
    [
        "authentication failed",
        "authentication required",
        "bad credentials",
        "could not read username",
        "could not read password",
        "fatal: authentication failed",
        "requires authentication",
        "terminal prompts disabled",
        "401 unauthorized",
        "403 forbidden",
    ]
    .iter()
    .any(|needle| lowered.contains(needle))
}

/// Decide whether an `apm install` failure is solely the experimental
/// `copilot-app` target refusing to lockfile-encode non-workflow primitives,
/// returning the count of such failures when so.
///
/// `apm install -g --target copilot,copilot-app` exits non-zero when the
/// experimental `copilot-app` target encounters a deployed primitive whose id
/// is outside its `apm--<owner>--<pkg>--<prompt>` workflow namespace (notably
/// `.agent.md` agent files shipped by third-party packages).  Those agents are
/// still installed correctly by the `copilot`/`vscode` targets, so this benign,
/// upstream-only limitation should not fail the task.
///
/// To avoid ever masking a genuine failure this fails closed: it returns
/// `Some(n)` only when apm's own reported error total parses *and* exactly
/// equals the number of workflow-encoding failure records.  Any unparseable
/// summary, or any additional error of a different kind, yields `None` so the
/// failure propagates normally.
///
/// This is only meaningful for the fixed `copilot,copilot-app` target
/// set used by [`run_apm_install`]; the `copilot-app` target is the sole source
/// of the tolerated marker.
fn tolerable_workflow_encode_failures(message: &str) -> Option<usize> {
    let normalized = normalize_apm_output(message);
    let encode_failures = normalized
        .matches(APM_WORKFLOW_ENCODE_FAILURE_MARKER)
        .count();
    if encode_failures == 0 {
        return None;
    }
    match parse_apm_error_count(&normalized) {
        Some(total) if total == encode_failures => Some(encode_failures),
        _ => None,
    }
}

/// Collapse every run of whitespace (including newlines) to a single space so
/// console line-wrapping in captured apm output cannot split a marker phrase.
fn normalize_apm_output(message: &str) -> String {
    message.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Parse the total error count from apm's summary line, e.g. the `7` in
/// `... with 7 error(s).`.  Returns `None` when no digit-prefixed ` error`
/// token is present so callers fail closed on unexpected output.
fn parse_apm_error_count(normalized: &str) -> Option<usize> {
    let idx = normalized.find(" error")?;
    let digits: String = normalized
        .get(..idx)?
        .chars()
        .rev()
        .take_while(char::is_ascii_digit)
        .collect::<Vec<char>>()
        .into_iter()
        .rev()
        .collect();
    digits.parse().ok()
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    reason = "test code uses panicking helpers"
)]
mod tests;
