//! Task: install AI plugin manifests via Microsoft APM.
//!
//! See <https://github.com/microsoft/apm>.  The dotfiles repo ships an
//! `apm/config/base.yml` under `symlinks/` which is linked to
//! `~/.apm/config/base.yml` by the
//! [`InstallSymlinks`](crate::tasks::files::symlinks::InstallSymlinks) task.  Overlay
//! repositories may symlink additional fragments into `~/.apm/config/*.yml`
//! (for example `~/.apm/config/work.yml`).
//!
//! Because `apm install -g --target copilot,vscode,copilot-app` always reads
//! the manifest at `~/.apm/apm.yml` regardless of cwd, this task merges every
//! `~/.apm/config/*.yml` fragment into a single generated `~/.apm/apm.yml`.
//! It then invokes
//! `apm install -g --target copilot,vscode,copilot-app` whenever install state
//! must be materialized, including ordinary up-to-date runs so local symlinked
//! plugin edits are redeployed to their real runtime locations.
//! Idempotency is provided by APM itself via its lockfile; the merged file is
//! regenerated deterministically every run.
//!
//! The experimental `copilot-app` target integrates hand-authored Copilot App
//! workflow prompts (`.prompt.md` files carrying workflow frontmatter) into
//! `~/.copilot`.  It is gated behind apm's experimental flag, persisted in the
//! machine-local `~/.apm/config.json`, so this task first runs the idempotent
//! `apm experimental enable copilot-app` (see `ensure_copilot_app_enabled`) to
//! keep fresh machines reproducible.  That step is best-effort: an older apm
//! without the subcommand simply logs a warning and the non-experimental
//! targets still install.  Verified against apm 0.16.0, where only `.prompt.md`
//! fragments with workflow frontmatter are encoded (under the `apm--` id
//! namespace); other primitives are left to the `copilot`/`vscode` targets.

use anyhow::{Context as _, Result};
use sha2::{Digest as _, Sha256};
use std::collections::HashSet;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use crate::tasks::{Context, Domain, Task, TaskPhase, TaskResult, task_deps};

mod autopilot;
mod fragments;
mod manifest;
mod outdated;

use autopilot::{
    DesiredApmWorkflows, apply_workflow_autopilot_fixup, snapshot_desired_apm_workflow_ids,
};
use fragments::{discover_fragment_files, discover_yaml_files, merge_fragments};
use manifest::{
    describe_dependencies, manifest_fingerprint, manifest_marker_matches,
    merged_manifest_needs_write, write_manifest_marker, write_merged_manifest,
};
use outdated::{
    ApmOutdatedCheck, ApmUpdateOutcome, outdated_output_has_updates, update_output_made_changes,
};

/// Header written at the top of the generated `~/.apm/apm.yml`.  The contents
/// are not meaningful to APM itself beyond providing a valid manifest, but
/// the warning helps anyone who opens the file by hand.
const GENERATED_HEADER: &str =
    "# Generated by dotfiles from ~/.apm/config/*.yml fragments.\n# Manual edits will be lost.\n";
const APM_TARGETS: &str = "copilot,vscode,copilot-app";
const APM_NONINTERACTIVE_ENV: &[(&str, &str)] = &[
    ("GIT_TERMINAL_PROMPT", "0"),
    ("GCM_INTERACTIVE", "Never"),
    ("GCM_GUI_PROMPT", "false"),
];
const APM_UP_TO_DATE_MARKER: &str = "all dependencies are up-to-date";
/// Marker `apm deps update` prints when no locked ref advanced.  Its absence
/// means at least one dependency was actually refreshed.
const APM_UPDATE_NO_CHANGES_MARKER: &str = "all packages already at latest refs";

/// Install and update AI plugin manifests via Microsoft APM.
#[derive(Debug)]
pub struct InstallApmPackages;

impl Task for InstallApmPackages {
    fn name(&self) -> &'static str {
        "Install APM packages"
    }

    fn phase(&self) -> TaskPhase {
        TaskPhase::Apply
    }

    fn domain(&self) -> Domain {
        Domain::Ai
    }

    task_deps![
        crate::tasks::packages::InstallPackages,
        crate::tasks::packages::InstallAurPackages,
        crate::tasks::files::symlinks::InstallSymlinks
    ];

    fn should_run(&self, ctx: &Context) -> bool {
        // Run whenever the symlinks layer ships fragments, or whenever
        // fragments have been linked into `~/.apm/config/`.
        let repo_config_dir = ctx
            .config_read()
            .root
            .join("symlinks")
            .join("apm")
            .join("config");
        match discover_yaml_files(&repo_config_dir) {
            Ok(fragments) if !fragments.is_empty() => return true,
            Ok(_) => {}
            Err(err) => {
                ctx.log.warn(&format!(
                    "could not inspect symlinks/apm/config; task will run to avoid hiding the \
                     error: {err:#}"
                ));
                return true;
            }
        }

        match discover_fragment_files(&ctx.home) {
            Ok(fragments) => !fragments.is_empty(),
            Err(err) => {
                ctx.log.warn(&format!(
                    "could not inspect ~/.apm/config; task will run to surface the error: {err:#}"
                ));
                true
            }
        }
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        if !ctx.dry_run && !ctx.executor.which("apm") {
            let reason = "apm not found in PATH; install it via `winget install Microsoft.APM` \
                          on Windows or the `apm-bin` AUR package on Arch Linux"
                .to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let fragments = discover_fragment_files(&ctx.home)?;
        if fragments.is_empty() {
            let reason = "no manifest fragments found under ~/.apm/config/".to_string();
            ctx.log.warn(&format!("skipping: {reason}"));
            return Ok(TaskResult::Skipped(reason));
        }

        let manifest_path = ctx.home.join(".apm").join("apm.yml");
        let lock_path = ctx.home.join(".apm").join("apm.lock.yaml");
        let marker_path = ctx.home.join(".apm").join(".dotfiles-manifest.sha256");
        let merged = merge_fragments(&fragments)?;
        let manifest_hash = manifest_fingerprint(&merged);
        let manifest_needs_write = merged_manifest_needs_write(&manifest_path, &merged)?;
        let lock_missing = !lock_path
            .try_exists()
            .with_context(|| format!("checking APM lockfile {}", lock_path.display()))?;
        let marker_missing_or_stale = !manifest_marker_matches(&marker_path, &manifest_hash)?;

        if ctx.dry_run {
            ctx.log
                .dry_run("run apm experimental enable copilot-app (idempotent) before install");
            ctx.log.dry_run(
                "re-assert apm-managed Copilot App workflows to autopilot + enabled in \
                 ~/.copilot/data.db after a successful install",
            );
            if manifest_needs_write {
                ctx.log.dry_run(&format!(
                    "merge {} APM manifest fragment(s) into {}",
                    fragments.len(),
                    manifest_path.display()
                ));
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} to sync changed manifest"
                ));
            } else if lock_missing {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} because {} is missing",
                    lock_path.display()
                ));
            } else if marker_missing_or_stale {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} because the current manifest has \
                     not been installed successfully yet"
                ));
            } else {
                ctx.log.dry_run(&format!(
                    "run apm install -g --target {APM_TARGETS} to redeploy current manifest content"
                ));
                ctx.log
                    .dry_run("run apm outdated -g and update only if dependencies are stale");
            }
            return Ok(TaskResult::DryRun);
        }

        let pre_workflows = snapshot_desired_apm_workflow_ids(ctx);
        ensure_copilot_app_enabled(ctx);

        if manifest_needs_write || lock_missing || marker_missing_or_stale {
            if manifest_needs_write {
                write_merged_manifest(&manifest_path, &merged)?;
            }
            let result = run_apm_install(ctx)?;
            if matches!(result, TaskResult::Ok) {
                ctx.log
                    .always(&format!("    install: {}", describe_dependencies(&merged)));
                write_manifest_marker(&marker_path, &manifest_hash)?;
                apply_workflow_autopilot_fixup(ctx, &pre_workflows);
            }
            return Ok(result);
        }

        // Unchanged manifest: redeploy locally symlinked plugins without
        // announcing a state change, matching the quiet idempotent convention
        // used by the other apply tasks.
        let result = run_apm_install(ctx)?;
        if !matches!(result, TaskResult::Ok) {
            return Ok(result);
        }
        write_manifest_marker(&marker_path, &manifest_hash)?;

        let outcome = match apm_dependencies_are_outdated(ctx)? {
            ApmOutdatedCheck::Outdated(true) => match run_apm_update(ctx)? {
                ApmUpdateOutcome::Changed => {
                    ctx.log.always("    update: APM dependencies");
                    TaskResult::Ok
                }
                ApmUpdateOutcome::Unchanged => {
                    ctx.log.debug("APM dependencies already at latest refs");
                    TaskResult::Ok
                }
                ApmUpdateOutcome::Skipped(reason) => TaskResult::Skipped(reason),
            },
            ApmOutdatedCheck::Outdated(false) => {
                ctx.log.debug("APM dependencies are up-to-date");
                TaskResult::Ok
            }
            ApmOutdatedCheck::Skipped(reason) => TaskResult::Skipped(reason),
        };
        apply_workflow_autopilot_fixup(ctx, &pre_workflows);
        Ok(outcome)
    }
}

/// Best-effort enable of the experimental `copilot-app` apm target.
///
/// The `copilot-app` target only encodes workflow prompts once apm's
/// experimental flag is set in the machine-local `~/.apm/config.json`.  Running
/// `apm experimental enable copilot-app` here keeps fresh machines reproducible
/// without a manual step.  The command is idempotent (it reports the flag is
/// already enabled on repeat runs), so it is safe to call on every apply.
///
/// Failure is intentionally non-fatal: an older apm that predates the
/// `experimental` subcommand will error, but the supported `copilot`/`vscode`
/// targets must still install.  Any error is logged as a warning and swallowed.
fn ensure_copilot_app_enabled(ctx: &Context) {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm experimental enable copilot-app` in {} (idempotent)",
            cwd.display()
        )
    });
    match ctx.executor.run_in_with_env(
        &cwd,
        "apm",
        &["experimental", "enable", "copilot-app"],
        APM_NONINTERACTIVE_ENV,
    ) {
        Ok(result) => report_apm_output(ctx, &result.stdout, &result.stderr),
        Err(err) => {
            let msg = format!("{err:#}");
            ctx.log.warn(&format!(
                "could not enable apm experimental copilot-app target; continuing without it \
                 (details: {})",
                msg.trim()
            ));
        }
    }
}

/// Install the current user-scope manifest without refreshing locked refs.
fn run_apm_install(ctx: &Context) -> Result<TaskResult> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm install -g --target {APM_TARGETS}` in {} (interactive credential prompts \
             disabled)",
            cwd.display()
        )
    });
    match ctx.executor.run_in_with_env(
        &cwd,
        "apm",
        &["install", "-g", "--target", APM_TARGETS],
        APM_NONINTERACTIVE_ENV,
    ) {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(TaskResult::Ok)
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm install requires GitHub authentication; run \
                              `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log
                    .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                Ok(TaskResult::Skipped(reason))
            } else {
                Err(err).context("running apm install")
            }
        }
    }
}

/// Return whether any locked user-scope dependency has a newer matching ref.
fn apm_dependencies_are_outdated(ctx: &Context) -> Result<ApmOutdatedCheck> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| format!("running `apm outdated -g` in {}", cwd.display()));
    match ctx
        .executor
        .run_in_with_env(&cwd, "apm", &["outdated", "-g"], APM_NONINTERACTIVE_ENV)
    {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            Ok(ApmOutdatedCheck::Outdated(outdated_output_has_updates(
                &result.stdout,
                &result.stderr,
            )))
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm outdated requires GitHub authentication; run \
                              `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log.warn(&format!(
                    "skipping APM update check: {reason} (details: {})",
                    msg.trim()
                ));
                Ok(ApmOutdatedCheck::Skipped(reason))
            } else {
                Err(err).context("checking for outdated APM dependencies")
            }
        }
    }
}

/// Refresh locked user-scope dependencies to the latest matching refs.
fn run_apm_update(ctx: &Context) -> Result<ApmUpdateOutcome> {
    let cwd = ctx.home.clone();
    ctx.debug_fmt(|| {
        format!(
            "running `apm deps update -g --target {APM_TARGETS}` in {} (interactive credential \
             prompts disabled)",
            cwd.display()
        )
    });
    match ctx.executor.run_in_with_env(
        &cwd,
        "apm",
        &["deps", "update", "-g", "--target", APM_TARGETS],
        APM_NONINTERACTIVE_ENV,
    ) {
        Ok(result) => {
            report_apm_output(ctx, &result.stdout, &result.stderr);
            if update_output_made_changes(&result.stdout, &result.stderr) {
                Ok(ApmUpdateOutcome::Changed)
            } else {
                Ok(ApmUpdateOutcome::Unchanged)
            }
        }
        Err(err) => {
            let msg = format!("{err:#}");
            if looks_like_auth_failure(&msg) {
                let reason = "apm update requires GitHub authentication; run \
                                  `gh auth login` or set GH_TOKEN/GITHUB_TOKEN and re-run"
                    .to_string();
                ctx.log
                    .warn(&format!("skipping: {reason} (details: {})", msg.trim()));
                Ok(ApmUpdateOutcome::Skipped(reason))
            } else {
                Err(err).context("updating APM dependencies")
            }
        }
    }
}

/// Relay raw APM command output to the diagnostic log file and the verbose
/// console.
///
/// The headline state-change is emitted separately as an always-visible
/// `    {verb}: {desc}` line by the caller, so this routes APM's own
/// line-by-line chatter through `debug`: it is always captured in the log
/// file and shown under `--verbose`, but stays out of the way on ordinary
/// runs.  APM provides idempotency itself via its lockfile, so this output is
/// purely informational.
fn report_apm_output(ctx: &Context, stdout: &str, stderr: &str) {
    for line in stdout.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.debug(trimmed);
    }
    for line in stderr.lines() {
        let trimmed = line.trim_end();
        if trimmed.trim().is_empty() {
            continue;
        }
        ctx.log.debug(trimmed);
    }
}

/// Heuristic: does an `apm install` failure message indicate a missing or
/// invalid GitHub credential rather than a real installation error?
fn looks_like_auth_failure(message: &str) -> bool {
    let lowered = message.to_lowercase();
    [
        "authentication failed",
        "authentication required",
        "bad credentials",
        "could not read username",
        "could not read password",
        "fatal: authentication failed",
        "requires authentication",
        "terminal prompts disabled",
        "401 unauthorized",
        "403 forbidden",
    ]
    .iter()
    .any(|needle| lowered.contains(needle))
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::panic,
    clippy::indexing_slicing,
    reason = "test code uses panicking helpers"
)]
mod tests {
    use super::autopilot::{WORKFLOW_AUTOPILOT_SCRIPT, WORKFLOW_DESIRED_IDS_SCRIPT};
    use super::*;
    use crate::exec::{ExecResult, MockExecutor};
    use crate::platform::{Os, Platform};
    use crate::tasks::test_helpers::{empty_config, make_context, make_linux_context};
    use std::sync::Arc;

    fn ok_result(stdout: &str) -> ExecResult {
        ExecResult {
            stdout: stdout.to_string(),
            stderr: String::new(),
            success: true,
            code: Some(0),
        }
    }

    const DEFAULT_FRAGMENT: &str =
        "name: base\nversion: 1.0.0\ndependencies:\n  apm:\n    - example/plugin\n";

    fn write_fragment(dir: &Path, filename: &str, content: &str) {
        std::fs::create_dir_all(dir).expect("create fragment dir");
        std::fs::write(dir.join(filename), content).expect("write manifest fragment");
    }

    fn write_repo_fragment(root: &Path, filename: &str, content: &str) {
        write_fragment(
            &root.join("symlinks").join("apm").join("config"),
            filename,
            content,
        );
    }

    fn write_home_fragment(home: &Path, filename: &str, content: &str) {
        write_fragment(&home.join(".apm").join("config"), filename, content);
    }

    fn write_default_home_fragment(home: &Path) {
        write_home_fragment(home, "base.yml", DEFAULT_FRAGMENT);
    }

    fn write_current_manifest_and_lock(home: &Path) {
        write_default_home_fragment(home);
        let fragments = discover_fragment_files(home).expect("discover fragments");
        let merged = merge_fragments(&fragments).expect("merge fragments");
        std::fs::write(home.join(".apm").join("apm.yml"), merged).expect("write manifest");
        std::fs::write(home.join(".apm").join("apm.lock.yaml"), "lock\n").expect("write lock");
    }

    fn write_current_manifest_lock_and_marker(home: &Path) {
        write_current_manifest_and_lock(home);
        let manifest =
            std::fs::read_to_string(home.join(".apm").join("apm.yml")).expect("read manifest");
        write_manifest_marker(
            &home.join(".apm").join(".dotfiles-manifest.sha256"),
            &manifest_fingerprint(&manifest),
        )
        .expect("write marker");
    }

    fn make_home_context(home: &Path) -> Context {
        make_linux_context(empty_config(home.to_path_buf())).with_home(home.to_path_buf())
    }

    fn make_home_context_with_executor(home: &Path, executor: MockExecutor) -> Context {
        make_context(
            empty_config(home.to_path_buf()),
            Platform::new(Os::Linux, false),
            Arc::new(executor),
        )
        .with_home(home.to_path_buf())
    }

    #[test]
    fn should_run_false_when_no_fragments() {
        let dir = tempfile::tempdir().expect("create temp dir");
        let ctx = make_home_context(dir.path());
        assert!(!InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn should_run_true_when_repo_yaml_fragment_exists() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_repo_fragment(dir.path(), "team.yaml", "name: test\n");
        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);
        assert!(InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn should_run_true_when_only_overlay_fragment_in_home() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "work.yml", "name: work\n");
        let ctx = make_home_context(dir.path());
        assert!(InstallApmPackages.should_run(&ctx));
    }

    #[test]
    fn run_skips_when_apm_not_found() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "base.yml", "name: base\n");

        let ctx = make_home_context(dir.path());
        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        match result {
            TaskResult::Skipped(reason) => assert!(
                reason.contains("apm not found"),
                "expected reason to mention 'apm not found', got {reason:?}"
            ),
            other => panic!("expected TaskResult::Skipped, got {other:?}"),
        }
    }

    #[test]
    fn run_installs_when_manifest_changed() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(
            dir.path(),
            "base.yml",
            "name: base\nversion: 1.0.0\ndependencies:\n  apm:\n    - github/awesome-copilot/plugins/project-planning\n",
        );

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                assert!(env.contains(&("GCM_INTERACTIVE", "Never")));
                assert!(env.contains(&("GCM_GUI_PROMPT", "false")));
                Ok(ok_result("installed\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after apm install, got {result:?}"
        );
        let manifest = std::fs::read_to_string(dir.path().join(".apm").join("apm.yml"))
            .expect("read merged manifest");
        assert!(manifest.contains("github/awesome-copilot/plugins/project-planning"));
    }

    /// Shared fragment that forces the changed-manifest install path.
    const AUTOPILOT_FIXTURE_FRAGMENT: &str = "name: base\nversion: 1.0.0\ndependencies:\n  apm:\n    - github/awesome-copilot/plugins/project-planning\n";

    /// Create `<home>/.copilot/data.db` so the autopilot fixup runs instead of
    /// short-circuiting on the missing-database gate.  Returns the db path.
    fn write_workflow_db(home: &Path) -> PathBuf {
        let copilot_dir = home.join(".copilot");
        std::fs::create_dir_all(&copilot_dir).expect("create .copilot dir");
        let db_path = copilot_dir.join("data.db");
        std::fs::write(&db_path, b"db").expect("write data.db");
        db_path
    }

    /// Queue the apm `which` + experimental-enable + install expectations shared
    /// by every autopilot-fixup test (the changed-manifest path).
    fn expect_apm_install(mock: &mut MockExecutor, seq: &mut mockall::Sequence) {
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(seq)
            .returning(|_, _, args, _| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(seq)
            .returning(|_, program, args, _| {
                assert_eq!(program, "apm");
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                Ok(ok_result("installed\n"))
            });
    }

    #[test]
    fn run_sets_apm_workflows_to_autopilot_after_install() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "base.yml", AUTOPILOT_FIXTURE_FRAGMENT);
        let db_path = write_workflow_db(dir.path());
        let db_str = db_path.to_str().expect("db path utf-8").to_string();

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        // python3 is probed twice: once for the pre-install snapshot and once
        // for the post-install fixup.
        mock.expect_which()
            .with(mockall::predicate::eq("python3"))
            .times(2)
            .returning(|_| true);
        // Pre-install snapshot: no apm--* rows are desired yet, so the diff in
        // the post-install fixup is a genuine "set 3" change.
        let pre_home = dir.path().to_path_buf();
        let pre_db = db_str.clone();
        mock.expect_run_unchecked_in()
            .once()
            .in_sequence(&mut seq)
            .returning(move |run_dir, program, args| {
                assert_eq!(run_dir, pre_home.as_path());
                assert_eq!(program, "python3");
                assert_eq!(args, ["-c", WORKFLOW_DESIRED_IDS_SCRIPT, pre_db.as_str()]);
                Ok(ok_result(""))
            });
        expect_apm_install(&mut mock, &mut seq);
        let post_home = dir.path().to_path_buf();
        mock.expect_run_unchecked_in()
            .once()
            .in_sequence(&mut seq)
            .returning(move |run_dir, program, args| {
                assert_eq!(run_dir, post_home.as_path());
                assert_eq!(program, "python3");
                assert_eq!(args, ["-c", WORKFLOW_AUTOPILOT_SCRIPT, db_str.as_str()]);
                Ok(ok_result("3 3\napm--a\napm--b\napm--c\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);
        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after autopilot fixup, got {result:?}"
        );
    }

    #[test]
    fn run_warns_when_python_missing_for_autopilot_fixup() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "base.yml", AUTOPILOT_FIXTURE_FRAGMENT);
        write_workflow_db(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        expect_apm_install(&mut mock, &mut seq);
        // Probed twice (pre-install snapshot + post-install fixup); both fall
        // back to `python` and then give up, so neither runs a query.
        mock.expect_which()
            .with(mockall::predicate::eq("python3"))
            .times(2)
            .returning(|_| false);
        mock.expect_which()
            .with(mockall::predicate::eq("python"))
            .times(2)
            .returning(|_| false);

        let ctx = make_home_context_with_executor(dir.path(), mock);
        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok when python is missing (non-fatal), got {result:?}"
        );
    }

    #[test]
    fn run_warns_when_workflow_db_is_locked() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_home_fragment(dir.path(), "base.yml", AUTOPILOT_FIXTURE_FRAGMENT);
        write_workflow_db(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("python3"))
            .times(2)
            .returning(|_| true);
        // Pre-install snapshot also hits the locked database and degrades to
        // Unavailable, so the post-install fixup stays quiet rather than
        // reporting a spurious change.
        mock.expect_run_unchecked_in()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, _| {
                Ok(ExecResult {
                    stdout: String::new(),
                    stderr: "database is locked".to_string(),
                    success: false,
                    code: Some(1),
                })
            });
        expect_apm_install(&mut mock, &mut seq);
        mock.expect_run_unchecked_in()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, _| {
                Ok(ExecResult {
                    stdout: String::new(),
                    stderr: "database is locked".to_string(),
                    success: false,
                    code: Some(1),
                })
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);
        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok despite locked db (non-fatal), got {result:?}"
        );
    }

    #[test]
    fn run_reinstalls_then_skips_update_when_manifest_lock_and_dependencies_are_current() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_lock_and_marker(dir.path());

        let mut seq = mockall::Sequence::new();
        let mut mock = MockExecutor::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("installed\n"))
            });
        let outdated_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, outdated_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["outdated", "-g"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[*] All dependencies are up-to-date\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after reinstalling current APM content, got {result:?}"
        );
    }

    #[test]
    fn run_updates_dependencies_when_outdated_reports_stale_lock() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_lock_and_marker(dir.path());

        let mut seq = mockall::Sequence::new();
        let mut mock = MockExecutor::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("installed\n"))
            });
        let outdated_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, _env| {
                assert_eq!(dir, outdated_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(args, ["outdated", "-g"]);
                Ok(ok_result("Outdated dependencies:\n- example/plugin\n"))
            });
        let update_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, env| {
                assert_eq!(dir, update_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(
                    args,
                    [
                        "deps",
                        "update",
                        "-g",
                        "--target",
                        "copilot,vscode,copilot-app"
                    ]
                );
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("updated\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after apm deps update, got {result:?}"
        );
    }

    #[test]
    fn run_stays_quiet_when_update_reports_no_changes() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_lock_and_marker(dir.path());

        let mut seq = mockall::Sequence::new();
        let mut mock = MockExecutor::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |_, _, args, _| {
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                Ok(ok_result("installed\n"))
            });
        // Branch/commit refs report an `unknown` status, so `apm outdated`
        // never prints the up-to-date marker and an update is attempted.
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |_, _, args, _| {
                assert_eq!(args, ["outdated", "-g"]);
                Ok(ok_result(
                    "[i] Some dependencies could not be checked (branch/commit refs)\n",
                ))
            });
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |_, _, args, _| {
                assert_eq!(
                    args,
                    [
                        "deps",
                        "update",
                        "-g",
                        "--target",
                        "copilot,vscode,copilot-app"
                    ]
                );
                Ok(ok_result("[*] All packages already at latest refs.\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok when update made no changes, got {result:?}"
        );
    }

    #[test]
    fn run_installs_when_success_marker_is_missing() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_current_manifest_and_lock(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        let install_cwd = dir.path().to_path_buf();
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(move |dir, program, args, _env| {
                assert_eq!(dir, install_cwd.as_path());
                assert_eq!(program, "apm");
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                Ok(ok_result("installed\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::Ok),
            "expected Ok after installing unmarked manifest, got {result:?}"
        );
        assert!(
            dir.path()
                .join(".apm")
                .join(".dotfiles-manifest.sha256")
                .exists(),
            "successful install should write the manifest success marker"
        );
    }

    #[test]
    fn run_dry_run_reports_planned_apm_work_without_writing() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let ctx = make_home_context(dir.path()).with_dry_run(true);

        let result = InstallApmPackages.run(&ctx).expect("run should not error");
        assert!(
            matches!(result, TaskResult::DryRun),
            "expected DryRun with fragments present, got {result:?}"
        );
        assert!(
            !dir.path().join(".apm").join("apm.yml").exists(),
            "dry-run must not write the generated manifest"
        );
    }

    #[test]
    fn run_skips_auth_failures() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, _, _| {
                Err(anyhow::anyhow!(
                    "fatal: Authentication failed; terminal prompts disabled"
                ))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages
            .run(&ctx)
            .expect("auth failure should skip");
        match result {
            TaskResult::Skipped(reason) => assert!(
                reason.contains("GitHub authentication"),
                "expected auth skip reason, got {reason:?}"
            ),
            other => panic!("expected TaskResult::Skipped, got {other:?}"),
        }
    }

    #[test]
    fn run_propagates_non_auth_apm_failures() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, env| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                assert!(env.contains(&("GIT_TERMINAL_PROMPT", "0")));
                Ok(ok_result("[!] copilot-app is already enabled.\n"))
            });
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, _, _| Err(anyhow::anyhow!("archive extraction failed")));

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let err = InstallApmPackages
            .run(&ctx)
            .expect_err("non-auth failures should propagate");
        assert!(
            format!("{err:#}").contains("archive extraction failed"),
            "expected propagated APM failure, got {err:#}"
        );
    }

    #[test]
    fn run_continues_when_experimental_enable_fails() {
        let dir = tempfile::tempdir().expect("create temp dir");
        write_default_home_fragment(dir.path());

        let mut mock = MockExecutor::new();
        let mut seq = mockall::Sequence::new();
        mock.expect_which()
            .with(mockall::predicate::eq("apm"))
            .once()
            .returning(|_| true);
        // A best-effort experimental-enable failure (e.g. an older apm without
        // the `experimental` subcommand) must never abort the install.
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, _| {
                assert_eq!(args, ["experimental", "enable", "copilot-app"]);
                Err(anyhow::anyhow!(
                    "error: unrecognized subcommand 'experimental'"
                ))
            });
        mock.expect_run_in_with_env()
            .once()
            .in_sequence(&mut seq)
            .returning(|_, _, args, _| {
                assert_eq!(
                    args,
                    ["install", "-g", "--target", "copilot,vscode,copilot-app"]
                );
                Ok(ok_result("installed\n"))
            });

        let ctx = make_home_context_with_executor(dir.path(), mock);

        let result = InstallApmPackages
            .run(&ctx)
            .expect("install should continue despite enable failure");
        assert!(matches!(result, TaskResult::Ok));
    }

    #[test]
    fn auth_failure_detection_matches_specific_auth_messages() {
        assert!(looks_like_auth_failure(
            "git failed: HTTP 403 Forbidden while fetching repository"
        ));
        assert!(looks_like_auth_failure(
            "fatal: Authentication failed; terminal prompts disabled"
        ));
    }

    #[test]
    fn auth_failure_detection_ignores_unrelated_credential_text() {
        assert!(!looks_like_auth_failure(
            "credential cache cleanup failed after archive extraction"
        ));
    }
}
