#!/bin/bash

if [[ -n $(command -v scrot) && -n $(command -v convert) && -n $(command -v playerctl) && -n $(command -v amixer) ]]
then

  # Make lock screen
  IMAGE=/tmp/i3lock.png
  ICON=~/.i3/i3lock-icon.png
  scrot $IMAGE
  convert $IMAGE -scale 10% -scale 1000% $IMAGE
  convert $IMAGE $ICON -gravity center -composite -matte $IMAGE

  # Pause player
  STATUS=$(playerctl status)
  playerctl pause

  # Mute
  SOUND=$(amixer sget Master | grep -E -o '\[on\]' | head -n 1)
  amixer -q set Master mute 2>/dev/null

  # Lock and wait
  i3lock -e -n -u -i $IMAGE &
  wait

  # Resume player
  if [[ $STATUS = "Playing" ]]
  then
    playerctl play
  fi

  # Unmute
  if [[ $SOUND == "[on]" ]]
  then
    amixer -q set Master unmute 2>/dev/null
  fi

  # Remove lock screen
  rm $IMAGE

else

  # Simple lock fallback
  i3lock -c 000000

fi
