#!/usr/bin/env python3
"""
Crypto Currency Ticker
"""

import sys
import requests

R = requests.get('https://api.coinbase.com/v2/prices/' + sys.argv[1] + '-USD/spot')
JSON = R.json()

print("${:,.2f}".format(float(JSON['data']['amount'])))
