#!/usr/bin/env python3
"""
Polybar Ethereum Module.
"""

import requests

R = requests.get('https://api.coinbase.com/v2/prices/ETH-USD/spot')
JSON = R.json()

print('$%.2f' % float(JSON['data']['amount']))
