#!/usr/bin/env python3
"""
Stock Price
"""

import sys
import requests

R = requests.get('https://api.iextrading.com/1.0/stock/' + sys.argv[1] + '/price')
price = R.text

print("${:,.2f}".format(float(price)))
