# vi: set ft=sh :

#
if [[ -d /etc/X11/xinit/xinitrc.d ]]
then
  for f in /etc/X11/xinit/xinitrc.d/*;
  do
    [[ -x "$f" ]] && . "$f"
  done
  unset f
fi

if [[ -x $(which i3 2>/dev/null) ]]
then

  # X preferences
  [[ -f ~/.Xresources ]] && xrdb ~/.Xresources
  xset s off
  xset -dpms
  xset s noblank

  # i3-gaps
  if [[ $(i3 -C) ]]
  then
    exec i3 -c ~/.i3/config-no-gaps
  else
    exec i3
  fi
fi
