#!/bin/sh

ignore=$(git remote show origin | sed -n -e 's/.*HEAD branch: //p')
branches=$(git branch --merged origin/HEAD 2>/dev/null)

# Delete branches merged to origin/HEAD
if [ -n "$branches" ]
then
  echo "$branches" | grep -E -v "(^\\*|$ignore)" | xargs -r -n 1 git branch -d
fi