#!/bin/sh

user=$(git config user.name)
remote=$(git config --get remote.origin.url)
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

# Skip for github repos you own
case $remote in
  *"git@github.com:$user/"* | *"https://github.com/$user"/*)
    exit
    ;;
esac

# Block pushing to master or main or develop
if [ "$branch" = "master" ] || [ "$branch" = "main" ] || [ "$branch" = "develop" ]
then
  echo "You are on branch $branch. Are you sure you want to push to this branch?"
  echo "If so, push with -n to bypass this pre-push hook."
  exit 1
fi