#!/bin/sh

github_user=$(git config github.user 2>/dev/null || git config github.username 2>/dev/null || true)
remote=${2:-}
remote_owner=

# Skip for GitHub repos you own.
case $remote in
  git@github.com:*)
    remote_owner=${remote#git@github.com:}
    remote_owner=${remote_owner%%/*}
    ;;
  https://github.com/*)
    remote_owner=${remote#https://github.com/}
    remote_owner=${remote_owner%%/*}
    ;;
  ssh://git@github.com/*)
    remote_owner=${remote#ssh://git@github.com/}
    remote_owner=${remote_owner%%/*}
    ;;
esac

if [ -n "$github_user" ] && [ "$remote_owner" = "$github_user" ]
then
  exit 0
fi

# Block updates to protected branches on repositories you do not own.
while read -r _local_ref _local_sha remote_ref _remote_sha
do
  case "$remote_ref" in
    refs/heads/master|refs/heads/main|refs/heads/develop)
      branch=${remote_ref#refs/heads/}
      echo "You are pushing to protected branch $branch."
      echo "Push with --no-verify to bypass this pre-push hook."
      exit 1
      ;;
  esac
done
