#!/usr/bin/env bash

# Delete branches merged to origin/HEAD
ignore=$(git remote show origin | sed -n -e 's/.*HEAD branch: //p')
git branch --merged origin/HEAD | grep -E -v "(^\\*|$ignore)" | xargs -r -n 1 git branch -d