#!/bin/sh
set -o errexit
set -o nounset

# -----------------------------------------------------------------------------
# test-docs.sh — Documentation consistency CI tests.
# Dependencies: test-helpers.sh
# Expected:     DIR (repository root)
# -----------------------------------------------------------------------------

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=lib/test-helpers.sh
. "$SCRIPT_DIR"/lib/test-helpers.sh

# List every tracked markdown file, one path relative to $DIR per line.
list_markdown_files() {
  if git -C "$DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "$DIR" ls-files '*.md'
  else
    ( cd "$DIR" && find . -type f -name '*.md' -not -path './.git/*' | sed 's|^\./||' )
  fi
}

# Print the link destinations of one markdown file, one per line.
#
# Only inline links and images are considered; reference definitions, bare URLs,
# and autolinks are out of scope.
extract_link_targets() {
  grep -oE '\]\([^)]+\)' "$1" 2>/dev/null | sed 's/^](//;s/)$//' || true
}

# Print the GitHub-style anchors generated by Markdown headings outside fenced
# code blocks. Duplicate headings receive the same numeric suffix GitHub uses.
markdown_anchors() {
  awk '
    /^[[:space:]]*```/ {
      if (fence == "") fence = "```"
      else if (fence == "```") fence = ""
      next
    }
    /^[[:space:]]*~~~/ {
      if (fence == "") fence = "~~~"
      else if (fence == "~~~") fence = ""
      next
    }
    fence == "" && /^#+[[:space:]]/ {
      marker = $1
      if (length(marker) > 6) next

      heading = $0
      sub(/^#+[[:space:]]+/, "", heading)
      sub(/[[:space:]]+#+[[:space:]]*$/, "", heading)
      slug = tolower(heading)
      gsub(/<[^>]*>/, "", slug)
      gsub(/[`*_~]/, "", slug)
      gsub(/[^[:alnum:] _-]/, "", slug)
      gsub(/ /, "-", slug)

      duplicate = seen[slug]++
      if (duplicate == 0) print slug
      else print slug "-" duplicate
    }
  ' "$1"
}

# Verify every relative Markdown link resolves to a file in the repository and
# every fragment names a heading in the target Markdown file.
#
# External links and mailto targets are skipped.
docs_links()
{(
  log_stage "Checking documentation links"
  failures=0
  checked=0
  anchors_checked=0

  for doc in $(list_markdown_files); do
    doc_dir="$(dirname "$DIR/$doc")"
    for target in $(extract_link_targets "$DIR/$doc"); do
      case "$target" in
        http://*|https://*|mailto:*|'<'*) continue ;;
      esac

      fragment=""
      case "$target" in
        *'#'*) fragment="${target#*#}" ;;
      esac

      # Drop any anchor or query suffix before resolving the file path.
      path="${target%%#*}"
      path="${path%%\?*}"

      if [ -z "$path" ]; then
        resolved="$DIR/$doc"
      else
        case "$path" in
          /*) resolved="$DIR$path" ;;
          *) resolved="$doc_dir/$path" ;;
        esac
      fi

      checked=$((checked + 1))
      if [ ! -e "$resolved" ]; then
        printf "   %s: broken link -> %s\n" "$doc" "$target"
        failures=$((failures + 1))
        continue
      fi

      case "$resolved" in
        *.md)
          if [ -n "$fragment" ]; then
            anchors_checked=$((anchors_checked + 1))
            if ! markdown_anchors "$resolved" | grep -Fqx -e "$fragment"; then
              printf "   %s: broken anchor -> %s\n" "$doc" "$target"
              failures=$((failures + 1))
            fi
          fi
          ;;
      esac
    done
  done

  log_verbose "Checked $checked relative links and $anchors_checked anchors"
  [ "$failures" -eq 0 ] || log_error "$failures broken documentation link(s) or anchor(s)"
)}

# Compare documentation to the real public catalog in an isolated Rust fixture.
docs_task_selectors()
{
  log_stage "Checking documented task selectors"
  (cd "$DIR/cli" && cargo test --quiet --profile ci --lib \
    app::commands::tasks::tests::documented_selectors_match_catalog -- --exact)
}

# Execute one or more tests when run directly: sh test-docs.sh <function_name>...
case "$0" in
  *test-docs.sh)
    for test_name in "$@"; do
      "$test_name"
    done
    ;;
esac
