//! Task: generate and install shell completions for the dotfiles CLI.
use anyhow::Result;

use crate::engine::{
    Context, Operation, OperationState, Task, TaskResult, TaskStats, process_operation,
};

/// Filename of the generated zsh completion script.
const ZSH_COMPLETION_FILENAME: &str = "_dotfiles";

/// Relative path within the symlinks directory to the zsh completions folder.
const ZSH_COMPLETIONS_SUBDIR: &str = "config/zsh/completions";

struct ZshCompletionOperation<'a> {
    content: &'a str,
}

#[derive(Debug)]
struct ZshCompletionPlan {
    destination: std::path::PathBuf,
    content: String,
}

impl ZshCompletionOperation<'_> {
    fn destination(ctx: &Context) -> std::path::PathBuf {
        ctx.paths()
            .symlinks_dir()
            .join(ZSH_COMPLETIONS_SUBDIR)
            .join(ZSH_COMPLETION_FILENAME)
    }
}

impl Operation for ZshCompletionOperation<'_> {
    type Plan = ZshCompletionPlan;

    fn current_state(&self, ctx: &Context) -> Result<OperationState<Self::Plan>> {
        let dest = Self::destination(ctx);
        let content = self.content.to_string();

        if dest.exists()
            && let Ok(existing) = std::fs::read_to_string(&dest)
            && existing == content
        {
            return Ok(OperationState::Complete);
        }

        Ok(OperationState::needs_run(
            format!("write {}", dest.display()),
            ZshCompletionPlan {
                destination: dest,
                content,
            },
        ))
    }

    fn preview(&self, ctx: &Context, plan: &Self::Plan) -> Result<TaskResult> {
        ctx.log()
            .dry_run(&format!("write {}", plan.destination.display()));
        Ok(TaskStats::changed().finish())
    }

    fn apply(&self, ctx: &Context, plan: &Self::Plan) -> Result<TaskResult> {
        crate::infra::fs::write_with_parent(&plan.destination, &plan.content)?;
        ctx.log().info("zsh completions written");
        Ok(TaskResult::Ok)
    }
}

/// Install shell completions for the dotfiles CLI by writing the pre-generated
/// zsh completion script into the repo's symlinks directory so it is available
/// through the existing symlink at `~/.config/zsh/completions/`.
///
/// The completion script content is generated by the application layer (which
/// owns the CLI definition) and injected here, keeping this domain task free of
/// any dependency on the CLI argument parser.
///
/// On non-Linux platforms the task is a no-op because the managed zsh
/// completions directory is only present in the Linux symlink layout.
#[derive(Debug)]
pub struct GenerateCompletions {
    /// The generated zsh completion script content.
    content: String,
}

impl GenerateCompletions {
    /// Create the task with the pre-generated zsh completion script content.
    #[must_use]
    pub const fn new(content: String) -> Self {
        Self { content }
    }
}

impl Task for GenerateCompletions {
    fn name(&self) -> &'static str {
        "Install shell completions"
    }

    fn should_run(&self, ctx: &Context) -> bool {
        ctx.system().platform().is_linux()
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        process_operation(
            ctx,
            &ZshCompletionOperation {
                content: &self.content,
            },
        )
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    reason = "test code uses panicking helpers"
)]
mod tests {
    use super::*;
    use crate::engine::Task;
    use crate::infra::platform::Os;
    use crate::test_helpers::{ContextBuilder, empty_config, make_linux_context};
    use std::path::PathBuf;

    const SAMPLE_COMPLETION: &str = "#compdef dotfiles\n# generated completion for dotfiles\n";

    fn task() -> GenerateCompletions {
        GenerateCompletions::new(SAMPLE_COMPLETION.to_string())
    }

    // ------------------------------------------------------------------
    // should_run
    // ------------------------------------------------------------------

    #[test]
    fn should_run_false_on_windows() {
        let config = empty_config(PathBuf::from("/repo"));
        let ctx = ContextBuilder::new(config).os(Os::Windows).build();
        assert!(!task().should_run(&ctx));
    }

    #[test]
    fn should_run_true_on_linux() {
        let config = empty_config(PathBuf::from("/repo"));
        let ctx = make_linux_context(config);
        assert!(task().should_run(&ctx));
    }

    // ------------------------------------------------------------------
    // run — real filesystem
    // ------------------------------------------------------------------

    #[test]
    fn run_writes_completion_file() {
        let dir = tempfile::tempdir().unwrap();
        let completions_dir = dir.path().join("symlinks").join(ZSH_COMPLETIONS_SUBDIR);
        std::fs::create_dir_all(&completions_dir).unwrap();

        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);

        let result = task().run(&ctx).unwrap();
        assert!(matches!(result, TaskResult::Ok));

        let dest = completions_dir.join(ZSH_COMPLETION_FILENAME);
        assert!(dest.exists(), "completion file should be written");

        let content = std::fs::read_to_string(&dest).unwrap();
        assert!(
            content.contains("dotfiles"),
            "generated script should reference the binary name"
        );
    }

    #[test]
    fn run_is_idempotent() {
        let dir = tempfile::tempdir().unwrap();
        let completions_dir = dir.path().join("symlinks").join(ZSH_COMPLETIONS_SUBDIR);
        std::fs::create_dir_all(&completions_dir).unwrap();

        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);

        // First run writes the file.
        drop(task().run(&ctx).unwrap());
        let mtime1 = std::fs::metadata(completions_dir.join(ZSH_COMPLETION_FILENAME))
            .unwrap()
            .modified()
            .unwrap();

        // Second run should be a no-op (same content → same mtime).
        drop(task().run(&ctx).unwrap());
        let mtime2 = std::fs::metadata(completions_dir.join(ZSH_COMPLETION_FILENAME))
            .unwrap()
            .modified()
            .unwrap();

        assert_eq!(mtime1, mtime2, "second run should not modify the file");
    }

    #[test]
    fn run_creates_parent_directory_if_missing() {
        let dir = tempfile::tempdir().unwrap();
        // Do NOT pre-create the completions directory.
        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config);

        let result = task().run(&ctx).unwrap();
        assert!(matches!(result, TaskResult::Ok));

        let dest = dir
            .path()
            .join("symlinks")
            .join(ZSH_COMPLETIONS_SUBDIR)
            .join(ZSH_COMPLETION_FILENAME);
        assert!(dest.exists(), "completion file should be created");
    }

    #[test]
    fn run_dry_run_returns_planned_change_without_writing() {
        let dir = tempfile::tempdir().unwrap();
        let config = empty_config(dir.path().to_path_buf());
        let ctx = make_linux_context(config).with_dry_run(true);

        let result = task().run(&ctx).unwrap();
        assert!(matches!(
            result,
            TaskResult::Batch(stats) if stats.changed > 0
        ));

        let dest = dir
            .path()
            .join("symlinks")
            .join(ZSH_COMPLETIONS_SUBDIR)
            .join(ZSH_COMPLETION_FILENAME);
        assert!(!dest.exists(), "dry-run should not write the file");
    }
}
