//! Task: generate and install shell completions for the dotfiles CLI.
use anyhow::Result;

use crate::engine::{
    Context, Operation, OperationState, Task, TaskMeta, TaskResult, TaskStats, process_operation,
};
use crate::infra::logging::OutputExt as _;

/// Filename of the generated zsh completion script.
const ZSH_COMPLETION_FILENAME: &str = "_dotfiles";

/// Relative path within the symlinks directory to the zsh completions folder.
const ZSH_COMPLETIONS_SUBDIR: &str = "config/zsh/completions";

/// Filename of the generated PowerShell completion script.
const POWERSHELL_COMPLETION_FILENAME: &str = "dotfiles-completions.ps1";

struct CompletionOperation<'a> {
    content: &'a str,
    destination: std::path::PathBuf,
    shell_name: &'static str,
}

impl Operation for CompletionOperation<'_> {
    type Plan = ();

    fn current_state(&self, _ctx: &Context) -> Result<OperationState<Self::Plan>> {
        if self.destination.exists()
            && let Ok(existing) = std::fs::read_to_string(&self.destination)
            && existing == self.content
        {
            return Ok(OperationState::Complete);
        }

        Ok(OperationState::needs_run(()))
    }

    fn preview(&self, ctx: &Context, _plan: &Self::Plan) -> Result<TaskResult> {
        ctx.log()
            .dry_run(format!("write {}", self.destination.display()));
        Ok(TaskStats::changed().finish())
    }

    fn apply(&self, ctx: &Context, _plan: &Self::Plan) -> Result<TaskResult> {
        crate::infra::fs::write_with_parent(&self.destination, self.content)?;
        ctx.log()
            .info(format!("{} completions written", self.shell_name));
        Ok(TaskStats::changed().finish())
    }
}

/// Install shell completions for the dotfiles CLI by writing a pre-generated
/// script into the platform's managed shell configuration directory.
///
/// The completion script content is generated by the application layer (which
/// owns the CLI definition) and injected here, keeping this domain task free of
/// any dependency on the CLI argument parser.
///
#[derive(Debug)]
pub struct GenerateCompletions {
    /// The generated zsh completion script content.
    zsh_content: String,
    /// The generated PowerShell completion script content.
    powershell_content: String,
}

impl GenerateCompletions {
    /// Create the task with the pre-generated shell completion scripts.
    #[must_use]
    pub const fn new(zsh_content: String, powershell_content: String) -> Self {
        Self {
            zsh_content,
            powershell_content,
        }
    }
}

impl Task for GenerateCompletions {
    fn meta(&self) -> TaskMeta<'_> {
        TaskMeta::new("Shell completions").with_selector("completions")
    }

    fn should_run(&self, ctx: &Context) -> bool {
        ctx.platform().is_linux() || ctx.platform().is_windows()
    }

    fn run(&self, ctx: &Context) -> Result<TaskResult> {
        let operation = if ctx.platform().is_windows() {
            CompletionOperation {
                content: &self.powershell_content,
                destination: ctx
                    .home()
                    .join(".config")
                    .join("powershell")
                    .join("profile.d")
                    .join(POWERSHELL_COMPLETION_FILENAME),
                shell_name: "PowerShell",
            }
        } else {
            CompletionOperation {
                content: &self.zsh_content,
                destination: ctx
                    .symlinks_dir()
                    .join(ZSH_COMPLETIONS_SUBDIR)
                    .join(ZSH_COMPLETION_FILENAME),
                shell_name: "zsh",
            }
        };
        process_operation(ctx, &operation)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::Task;
    use crate::infra::platform::Os;
    use crate::test_helpers::{ContextBuilder, make_linux_context};
    use std::path::PathBuf;

    const SAMPLE_ZSH_COMPLETION: &str = "#compdef dotfiles\n# generated completion for dotfiles\n";
    const SAMPLE_POWERSHELL_COMPLETION: &str =
        "Register-ArgumentCompleter -Native -CommandName dotfiles\n";

    fn task() -> GenerateCompletions {
        GenerateCompletions::new(
            SAMPLE_ZSH_COMPLETION.to_string(),
            SAMPLE_POWERSHELL_COMPLETION.to_string(),
        )
    }

    // ------------------------------------------------------------------
    // should_run
    // ------------------------------------------------------------------

    #[test]
    fn should_run_true_on_windows() {
        let ctx = ContextBuilder::new(PathBuf::from("/repo"))
            .overlay(None)
            .os(Os::Windows)
            .build();
        assert!(task().should_run(&ctx));
    }

    #[test]
    fn should_run_true_on_linux() {
        let ctx = make_linux_context(PathBuf::from("/repo"), None);
        assert!(task().should_run(&ctx));
    }

    // ------------------------------------------------------------------
    // run — real filesystem
    // ------------------------------------------------------------------

    fn completion_fixture(os: Os) -> (tempfile::TempDir, Context, PathBuf, &'static str) {
        let dir = tempfile::tempdir_in(".").unwrap();
        let root = dir.path().join("repo");
        let home = dir.path().join("home");
        let ctx = ContextBuilder::new(root.clone())
            .overlay(None)
            .os(os)
            .build()
            .with_home(home.clone());
        let (destination, content) = if os == Os::Windows {
            (
                home.join(".config/powershell/profile.d")
                    .join(POWERSHELL_COMPLETION_FILENAME),
                SAMPLE_POWERSHELL_COMPLETION,
            )
        } else {
            (
                root.join("symlinks")
                    .join(ZSH_COMPLETIONS_SUBDIR)
                    .join(ZSH_COMPLETION_FILENAME),
                SAMPLE_ZSH_COMPLETION,
            )
        };
        (dir, ctx, destination, content)
    }

    #[test]
    fn completions_create_repair_and_converge_without_rewriting_current_content() {
        for os in [Os::Linux, Os::Windows] {
            for existing_parent in [false, true] {
                let (_dir, ctx, destination, expected) = completion_fixture(os);
                if existing_parent {
                    std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
                }
                crate::test_helpers::assert_task_changed(&task().run(&ctx).unwrap());
                assert_eq!(
                    std::fs::read_to_string(&destination).unwrap(),
                    expected,
                    "{os:?}"
                );

                std::fs::write(&destination, "stale completions").unwrap();
                crate::test_helpers::assert_task_changed(&task().run(&ctx).unwrap());
                assert_eq!(
                    std::fs::read_to_string(&destination).unwrap(),
                    expected,
                    "{os:?}"
                );

                let past = std::time::UNIX_EPOCH + std::time::Duration::from_secs(1_000_000_000);
                std::fs::File::options()
                    .write(true)
                    .open(&destination)
                    .unwrap()
                    .set_times(std::fs::FileTimes::new().set_modified(past))
                    .unwrap();
                let before = std::fs::metadata(&destination).unwrap().modified().unwrap();
                crate::test_helpers::assert_task_ok(&task().run(&ctx).unwrap());
                assert_eq!(
                    std::fs::metadata(&destination).unwrap().modified().unwrap(),
                    before,
                    "{os:?}: current content must not be rewritten"
                );
            }
        }
    }

    #[test]
    fn dry_run_preserves_missing_and_stale_completions() {
        for os in [Os::Linux, Os::Windows] {
            let (_dir, ctx, destination, _) = completion_fixture(os);
            let ctx = ctx.with_dry_run(true);
            crate::test_helpers::assert_task_changed(&task().run(&ctx).unwrap());
            assert!(
                !destination.parent().unwrap().exists(),
                "{os:?}: preview created directories"
            );

            std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
            std::fs::write(&destination, "stale completions").unwrap();
            crate::test_helpers::assert_task_changed(&task().run(&ctx).unwrap());
            assert_eq!(
                std::fs::read_to_string(&destination).unwrap(),
                "stale completions",
                "{os:?}"
            );
        }
    }

    #[test]
    fn blocked_completion_destination_fails_without_removing_existing_files() {
        for os in [Os::Linux, Os::Windows] {
            let (_dir, ctx, destination, _) = completion_fixture(os);
            std::fs::create_dir_all(&destination).unwrap();
            let unmanaged = destination.join("keep.txt");
            std::fs::write(&unmanaged, "preserve").unwrap();

            assert!(
                task().run(&ctx).is_err(),
                "{os:?}: directory destination must fail"
            );
            assert_eq!(
                std::fs::read_to_string(unmanaged).unwrap(),
                "preserve",
                "{os:?}"
            );
        }
    }
}
