#!/bin/bash

if [[ -d /etc/X11/xinit/xinitrc.d ]]
then
  for f in /etc/X11/xinit/xinitrc.d/*;
  do
    [[ -x "$f" ]] && . "$f"
  done
  unset f
fi

if [[ -n $(command -v i3) ]]
then

  # X preferences
  [[ -f ~/.Xresources ]] && xrdb ~/.Xresources
  xset s off
  xset -dpms
  xset s noblank

  # i3-gaps
  rm ~/.i3/config
  cat ~/.i3/config-base ~/.i3/config-with-gaps >> ~/.i3/config
  if [[ $(i3 -C) ]]
  then
    rm ~/.i3/config
    cat ~/.i3/config-base ~/.i3/config-without-gaps >> ~/.i3/config
    exec i3
  else
    exec i3
  fi
fi
