#!/bin/sh

# ~/bin
export PATH=$PATH:~/bin

# GOPATH
export PATH=$PATH:~/src/go/bin

# RubyGems
if [ -n "$(command -vp ruby)" ]
then
  PATH="$PATH:$(ruby -e 'print Gem.user_dir')/bin"
  export GEM_HOME=$HOME/.gem
fi