#!/bin/sh

if [ -n "$(command -vp wslpath)" ]
then
  WINDRIVE=$($(wslpath -a $(cmd.exe /c "echo %SYSTEMDRIVE%\\") 2>/dev/null) | sed "$s/..$//")
  export WINDRIVE

  WINHOME=$($(wslpath -a $(cmd.exe /c "echo %USERPROFILE%\\") 2>/dev/null) | sed "$s/..$//")
  export WINHOME
fi
