#!/usr/bin/env bash
# shellcheck shell=bash

PS1=""

# host name
# SSH_CONNECTION and HOSTNAME are standard environment variables
# Quoting is intentional for delayed evaluation in PS1
# shellcheck disable=SC2154,SC2070,SC2157,SC2086
PS1+="\\[\\e[0;36m\\]\\$([ -n \"$SSH_CONNECTION\" ] || [ -e /.dockerenv ] && echo \"$HOSTNAME \")"

# default shell
PS1+="\\[\\e[0;36m\\]\$([ \"\$(command -v bash)\" != \"\$SHELL\" ] && echo \"bash \")"

# working dir
PS1+="\\[\\e[0;33m\\]\\w"

# git prompt info
gitprompt="\\[\\e[0m\\]\$(git rev-parse --abbrev-ref HEAD 2>/dev/null)\\[\\e[0;31m\\]\$(git --no-optional-locks status --porcelain 2>/dev/null | wc -l | awk '{s=(\$1>0)?\"+\"\$1:\"\"; print s}')"
[ -n "$gitprompt" ] && PS1+=" $gitprompt"

# sudo active
PS1+="\\[\\e[0;36m\\]\$(sudo -n uptime 2>&1 | grep -c 'load' | awk '{s=(\$1>0)?\" !\":\"\"; print s}')"

# prompt
PS1+="\\n\\[\\e[0m\\]\\$ "
