#!/usr/bin/env bash

# History
mkdir -p ~/.cache/bash
export HISTFILE=~/.cache/bash/history

# Path
. ~/.config/shell/path.sh

# Aliases
. ~/.config/shell/aliases.sh

# GUI Aliases
[ -f ~/.config/shell/aliases-gui.sh ] && . ~/.config/shell/aliases-gui.sh

# Prompt
. ~/.config/bash/prompt