#!/usr/bin/env bash

# Global profile
[ -f /etc/profile ] && . /etc/profile

# Profile
. ~/.config/shell/profile.sh

# GUI Profile
[ -f ~/.config/shell/profile-gui.sh ] && . ~/.config/shell/profile-gui.sh
