#!/usr/bin/env bash

# History
mkdir -p ~/.cache/bash
export HISTFILE=~/.cache/bash/history
export HISTSIZE=10000
export HISTFILESIZE=10000
shopt -s histappend
shopt -s checkwinsize

# Path
. ~/.config/shell/path.sh

# Aliases
. ~/.config/shell/aliases.sh

# GUI Aliases
[ -f ~/.config/shell/aliases-gui.sh ] && . ~/.config/shell/aliases-gui.sh

# Prompt
. ~/.config/bash/prompt