#!/usr/bin/env zsh

# Quiet
setopt no_beep
setopt NO_LIST_BEEP
set bell-style none

# Word Style
autoload -Uz select-word-style
select-word-style bash

# Colors
autoload -Uz colors
colors

# History
setopt histignorealldups
setopt incappendhistory
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

# Various options
setopt autocd
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome

# Path
. ~/.shell/path.sh

# Aliases
. ~/.shell/aliases.sh

# Prompt
. ~/.zsh/prompt.zsh

# Completion
. ~/.zsh/completion.zsh

# Key bindings
. ~/.zsh/key-bindings.zsh

# Plugins
. ~/.zsh/plugins/*

# Functions
fpath=(~/.zsh/functions $fpath)
autoload -Uz ~/.zsh/functions/*
