#!/usr/bin/env zsh

# Quiet
setopt no_beep
setopt NO_LIST_BEEP
set bell-style none

# Word Style
autoload -Uz select-word-style
select-word-style bash

# Colors
autoload -Uz colors
colors

# History
setopt histignorealldups
setopt sharehistory
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_verify
mkdir -p ~/.cache/zsh
HISTFILE=~/.cache/zsh/history
HISTSIZE=10000
SAVEHIST=10000

# Various options
setopt autocd
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome

# Path
. ~/.config/shell/path.sh

# Aliases
. ~/.config/shell/aliases.sh

# GUI Aliases
[ -f ~/.config/shell/aliases-gui.sh ] && . ~/.config/shell/aliases-gui.sh

# Prompt
. ~/.config/zsh/prompt.zsh

# Completion
. ~/.config/zsh/completion.zsh

# Key bindings
. ~/.config/zsh/key-bindings.zsh

# Plugins
for plugin in ~/.config/zsh/plugins/*.zsh; do
  [ -f "$plugin" ] && . "$plugin"
done

# Functions
fpath=(~/.config/zsh/functions $fpath)
autoload -Uz ~/.config/zsh/functions/*
