# vi set ft=zsh :

# Quiet
setopt no_beep
setopt NO_LIST_BEEP
set bell-style none

# Word Style
autoload -U select-word-style
select-word-style bash

# Colors
autoload -U colors
colors

# History
setopt histignorealldups
setopt incappendhistory
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

# Various options
setopt autocd
setopt autopushd
setopt pushdminus
setopt pushdsilent
setopt pushdtohome

# Prompt
[[ -e ~/.zsh/prompt ]] && . ~/.zsh/prompt

# Completion
[[ -e ~/.zsh/completion ]] && . ~/.zsh/completion

# Key bindings
[[ -e ~/.zsh/key-bindings ]] && . ~/.zsh/key-bindings

# Plugins
[[ -d ~/.zsh/plugins ]] && . ~/.zsh/plugins/*

[[ -d ~/.shell/interactive ]] && for f in ~/.shell/interactive/*; do . "$f"; done